import type { ComponentType } from "react";
import type { Lng } from "@/i18n";
import manifest from "@/data/content-manifest.json";

// ── Types ───────────────────────────────────────────────────────────────────

export type ContentTier = "free" | "pro" | "paid";
export type ContentCollection = "academy" | "blog" | "toolkits";

export interface QuizQuestion {
  q: string;
  options: string[];
  /** index into `options` of the correct answer */
  answer: number;
}

export interface ContentFrontmatter {
  title: string;
  slug: string;
  lang: Lng;
  tier: ContentTier;
  category: string;
  seoDescription?: string;
  updatedAt?: string;
  quiz?: QuizQuestion[];
}

export interface ContentEntry extends ContentFrontmatter {
  collection: ContentCollection;
  /**
   * Compiled MDX body component. Only present for collections rendered on the
   * client (blog). Academy/toolkits bodies are server-gated (see GatedContent)
   * and are deliberately NOT bundled — so Pro/paid prose never ships to guests.
   */
  Component?: ComponentType<Record<string, unknown>>;
  /** Estimated reading time in minutes (precomputed in the manifest). */
  readMinutes: number;
}

// ── Metadata from the build-time manifest (no bodies) ─────────────────────────
// client/src/data/content-manifest.json is generated by script/gen-content-manifest.ts
// (run via `npm run gen:content`, and automatically in the build). It carries
// frontmatter + reading time ONLY — no compiled bodies, no raw prose — so the
// public bundle never contains gated academy/toolkit content.

// ── Blog bodies only (free, rendered client-side by BlogPost) ─────────────────
// Academy/toolkit prose is fetched per-request from the server-gated endpoint,
// so we only eager-import the free blog bodies here.
type MdxModule = { default: ComponentType<Record<string, unknown>> };
const blogModules = import.meta.glob<MdxModule>("../../../content/blog/**/*.mdx", {
  eager: true,
});

const BLOG_RE = /\/content\/blog\/(.+)\.(vi|en)\.mdx$/;
const blogComponents = new Map<string, ComponentType<Record<string, unknown>>>();
for (const p in blogModules) {
  const m = p.match(BLOG_RE);
  if (m) blogComponents.set(`${m[1]}.${m[2]}`, blogModules[p].default);
}

const entries: ContentEntry[] = (manifest as Array<Omit<ContentEntry, "Component">>).map(
  (e) => ({
    ...e,
    Component:
      e.collection === "blog"
        ? blogComponents.get(`${e.slug}.${e.lang}`)
        : undefined,
  }),
);

// ── Public API ───────────────────────────────────────────────────────────────

export interface ListOptions {
  collection?: ContentCollection;
  lang?: Lng;
  tier?: ContentTier;
}

/** List content entries, filtered by collection / language / tier. */
export function listContent(opts: ListOptions = {}): ContentEntry[] {
  return entries
    .filter((e) => (opts.collection ? e.collection === opts.collection : true))
    .filter((e) => (opts.lang ? e.lang === opts.lang : true))
    .filter((e) => (opts.tier ? e.tier === opts.tier : true))
    .sort((a, b) => a.title.localeCompare(b.title));
}

/** Get one entry by collection + slug + language. */
export function getContentBySlug(
  collection: ContentCollection,
  slug: string,
  lang: Lng,
): ContentEntry | undefined {
  return entries.find(
    (e) => e.collection === collection && e.slug === slug && e.lang === lang,
  );
}

/** All distinct slugs in a collection (language-agnostic). */
export function listSlugs(collection: ContentCollection): string[] {
  return Array.from(
    new Set(entries.filter((e) => e.collection === collection).map((e) => e.slug)),
  );
}
