import { ArrowLeft, ArrowRight, CheckCircle2, CircleDashed, FlaskConical, Layers3, ShieldAlert } from "lucide-react";
import { Link } from "wouter";
import { assessApplicationPack, testMethodApplicationPacks, type ApplicationDimensionStatus, type ApplicationPackStage } from "@/data/testMethodApplications";
import { useSEO } from "@/hooks/use-seo";

const stageLabel: Record<ApplicationPackStage, string> = { "application-development": "Application development", "content-foundation": "Content foundation", "specialist-gated": "Specialist gated" };
const statusLabel: Record<ApplicationDimensionStatus, string> = { structured: "Structured", partial: "Partial", "evidence-required": "Evidence required" };
const statusStyle: Record<ApplicationDimensionStatus, string> = { structured: "border-teal-300/25 bg-teal-300/10 text-teal-200", partial: "border-sky-300/20 bg-sky-300/10 text-sky-200", "evidence-required": "border-amber-300/20 bg-amber-300/10 text-amber-200" };

export default function QualityLabMethodApplicationsPage() {
  useSEO({ title: "Test Method Application Packs | Atlas Quality Lab", description: "Inspect how Atlas develops test methods from educational content into evidence-linked, application-specific Method Graph nodes." });
  return <div className="min-h-screen bg-[#08111f] px-4 pb-24 pt-8 text-slate-100 md:pt-14"><div className="mx-auto max-w-7xl">
    <Link href="/quality-lab/evidence" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4" /> Atlas Evidence Graph</Link>
    <header className="mt-6 overflow-hidden rounded-3xl border border-teal-300/20 bg-gradient-to-br from-teal-300/10 via-sky-300/[0.06] to-transparent p-6 md:p-10">
      <span className="inline-flex items-center gap-2 rounded-full border border-teal-300/25 bg-teal-300/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.18em] text-teal-200"><FlaskConical className="h-4 w-4" /> Application intelligence</span>
      <h1 className="mt-6 max-w-5xl font-display text-4xl font-bold leading-tight md:text-6xl">A test name becomes useful only when its application is explicit.</h1>
      <p className="mt-5 max-w-4xl text-base leading-8 text-slate-300 md:text-lg">Atlas separates educational coverage from executable Method Graph maturity. Each pack must connect intended use, matrix, method architecture, decision rules, resources and lifecycle evidence before it can drive a controlled Blueprint.</p>
      <div className="mt-6 flex gap-3 rounded-xl border border-amber-300/15 bg-amber-300/[0.04] p-4 text-xs leading-6 text-slate-400"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-200" /><p><strong className="text-slate-200">No generic method approval:</strong> these records expose current coverage and missing evidence. Site specifications, approved procedures, suitability/validation and qualified review remain authoritative.</p></div>
    </header>
    <section className="mt-8 grid gap-5">{testMethodApplicationPacks.map((pack) => { const assessment=assessApplicationPack(pack); return <article key={pack.id} className="rounded-3xl border border-white/10 bg-slate-950/35 p-5 md:p-7">
      <div className="flex flex-col gap-4 border-b border-white/10 pb-5 md:flex-row md:items-start md:justify-between"><div className="flex gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-white/10 bg-white/[0.04] font-bold text-teal-200">{pack.sequence}</div><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">{pack.domain}</p><h2 className="mt-1 text-2xl font-bold">{pack.title}</h2></div></div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-sky-300/20 bg-sky-300/[0.07] px-3 py-1 text-[10px] font-bold uppercase text-sky-200">{stageLabel[pack.stage]}</span><span className="rounded-full border border-white/10 bg-white/[0.035] px-3 py-1 text-[10px] font-bold uppercase text-slate-400">{pack.methodGraphStatus.replaceAll("-", " ")}</span></div></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-white/8 bg-black/15 p-4"><p className="text-[9px] font-bold uppercase tracking-wider text-teal-300">Quality decision</p><p className="mt-2 text-sm leading-7 text-slate-300">{pack.decision}</p></div><div className="rounded-xl border border-white/8 bg-black/15 p-4"><p className="text-[9px] font-bold uppercase tracking-wider text-amber-300">Current boundary</p><p className="mt-2 text-sm leading-7 text-slate-400">{pack.boundary}</p></div></div>
      <div className="mt-5 grid gap-3 lg:grid-cols-3">{pack.dimensions.map((dimension)=><section key={dimension.id} className="flex flex-col rounded-2xl border border-white/8 bg-white/[0.025] p-4"><div className="flex items-start justify-between gap-2">{dimension.status === "structured" ? <CheckCircle2 className="h-5 w-5 text-teal-300" /> : <CircleDashed className="h-5 w-5 text-slate-500" />}<span className={`rounded-full border px-2 py-1 text-[8px] font-bold uppercase ${statusStyle[dimension.status]}`}>{statusLabel[dimension.status]}</span></div><h3 className="mt-4 text-sm font-bold">{dimension.label}</h3><p className="mt-2 flex-1 text-xs leading-6 text-slate-500">{dimension.currentBasis}</p><div className="mt-4 border-t border-white/8 pt-3"><p className="text-[9px] font-bold uppercase tracking-wider text-amber-300/70">Exit evidence</p><p className="mt-1 text-[11px] leading-5 text-slate-400">{dimension.exitEvidence}</p></div></section>)}</div>
      <div className="mt-5 flex flex-col gap-4 rounded-xl border border-white/8 bg-black/15 p-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold text-slate-200">Executable eligibility: {assessment.readyForExecutableMethodGraph ? "Ready for controlled implementation review" : `${assessment.blockers.length} evidence blocker${assessment.blockers.length === 1 ? "" : "s"} remain`}</p><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1">{pack.evidenceHrefs.map((href)=><Link key={href} href={href} className="text-[10px] font-semibold text-sky-300 hover:text-sky-200">Supporting evidence <ArrowRight className="inline h-3 w-3" /></Link>)}</div></div><Link href={pack.guideHref} className="inline-flex shrink-0 items-center gap-2 text-xs font-bold text-teal-300">Open application guide <ArrowRight className="h-4 w-4" /></Link></div>
    </article>; })}</section>
    <section className="mt-8 rounded-3xl border border-sky-300/20 bg-sky-300/[0.05] p-6 md:p-8"><Layers3 className="h-6 w-6 text-sky-300" /><h2 className="mt-4 text-2xl font-bold">The next step is controlled application evidence, not more generic method summaries.</h2><p className="mt-2 max-w-4xl text-sm leading-7 text-slate-400">Use the Application Evidence Readiness Register to resolve each dimension, then capture touch time, equipment occupancy, BOM, queues and exceptions in the Method Execution Observation template. Only reviewed cases should enter validation and rule-learning review.</p><Link href="/quality-lab/discovery-pack" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-sky-300">Collect application evidence <ArrowRight className="h-4 w-4" /></Link></section>
  </div></div>;
}
