import { FormEvent, useEffect, useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import { ArrowLeft, CheckCircle2, ClipboardCheck, Download, Plus, ShieldCheck } from "lucide-react";
import { useSEO } from "@/hooks/use-seo";
import { analytics } from "@/hooks/use-analytics";
import { fetchQualityLabReviewedProject, fetchQualityLabReviewedProjectRevisions, getQualityLabProject, syncQualityLabReviewedProject } from "@/lib/quality-lab-projects";
import { downloadCalibration, downloadEngagement, getOrCreateEngagement, saveEngagement, setEngagementActual } from "@/lib/quality-lab-engagements";
import { summarizeCalibration, varianceMagnitude, type CalibrationMetricKey, type QualityLabEngagementPacket } from "@shared/quality-lab-engagement";
import { useUser } from "@/context/UserContext";
import type { QualityLabProject } from "@shared/quality-lab";

const inputClass = "w-full rounded-lg border border-white/10 bg-slate-950/60 px-3 py-2 text-sm text-white outline-none focus:border-teal-300/50";
const baselineLabels: Record<keyof QualityLabEngagementPacket["baseline"], string> = { monthlyTests: "Monthly tests", teamFte: "Team FTE", areaSqm: "Area (m²)", capexLowUsd: "CAPEX low (USD)", capexHighUsd: "CAPEX high (USD)" };

export default function QualityLabEngagementPage() {
  const [, params] = useRoute("/quality-lab/engagements/:id");
  const localProject = useMemo(() => params?.id ? getQualityLabProject(params.id) : undefined, [params?.id]);
  const { isAuthenticated } = useUser();
  const [recoveredProject, setRecoveredProject] = useState<QualityLabProject | null>(null);
  const [revisions, setRevisions] = useState<Array<{ revisionNumber: number; createdAt: string; blockingOpenCount: number }>>([]);
  const project = localProject ?? recoveredProject ?? undefined;
  const [packet, setPacket] = useState<QualityLabEngagementPacket | null>(() => localProject ? getOrCreateEngagement(localProject) : null);
  const [correction, setCorrection] = useState({ fieldOrRuleId: "", previousValue: "", correctedValue: "", evidenceRef: "", rationale: "", reviewerRole: "" });
  const [decision, setDecision] = useState({ decision: "", rationale: "", owner: "", downstreamImpact: "", options: "" });
  useSEO({ title: "Blueprint Engagement Workspace", description: "Resolve evidence, record corrections and capture project decisions for an Atlas Quality Lab Blueprint.", noIndex: true });

  useEffect(() => {
    if (localProject) { setRecoveredProject(null); setPacket(getOrCreateEngagement(localProject)); return; }
    if (!isAuthenticated || !params?.id) return;
    let active = true;
    fetchQualityLabReviewedProject(params.id).then((snapshot) => {
      if (!active || !snapshot) return;
      const recovered: QualityLabProject = {
        id: snapshot.localProjectId, name: snapshot.projectName, input: snapshot.input, blueprint: snapshot.blueprint,
        createdAt: snapshot.blueprint.generatedAt, updatedAt: snapshot.blueprint.generatedAt, reviewRequestedAt: snapshot.reviewRequestedAt ?? undefined,
      };
      setRecoveredProject(recovered);
      setPacket(snapshot.engagement ?? getOrCreateEngagement(recovered));
    }).catch(() => undefined);
    return () => { active = false; };
  }, [isAuthenticated, localProject, params?.id]);

  useEffect(() => {
    if (!isAuthenticated || !project?.reviewRequestedAt) return;
    fetchQualityLabReviewedProjectRevisions(project.id).then(setRevisions).catch(() => undefined);
  }, [isAuthenticated, project?.id, project?.reviewRequestedAt]);

  if (!project || !packet) return <div className="mx-auto max-w-2xl px-4 py-20 text-center"><h1 className="text-2xl font-bold">{isAuthenticated ? "Loading reviewed project…" : "Engagement project not found"}</h1><Link href="/quality-lab/projects" className="mt-5 inline-block text-teal-300">Open saved projects</Link></div>;

  function persist(next: QualityLabEngagementPacket) { const saved = saveEngagement(next); const reviewedProject = project; setPacket(saved); if (isAuthenticated && reviewedProject?.reviewRequestedAt) syncQualityLabReviewedProject(reviewedProject, saved).catch(() => undefined); }
  function addCorrection(event: FormEvent) {
    event.preventDefault();
    persist({ ...packet!, corrections: [...packet!.corrections, { id: `cor_${Date.now().toString(36)}`, recordedAt: new Date().toISOString(), ...correction }] });
    setCorrection({ fieldOrRuleId: "", previousValue: "", correctedValue: "", evidenceRef: "", rationale: "", reviewerRole: "" });
  }
  function addDecision(event: FormEvent) {
    event.preventDefault();
    persist({ ...packet!, decisions: [...packet!.decisions, { id: `dec_${Date.now().toString(36)}`, recordedAt: new Date().toISOString(), decision: decision.decision, rationale: decision.rationale, owner: decision.owner, downstreamImpact: decision.downstreamImpact, optionsConsidered: decision.options.split("\n").map((v) => v.trim()).filter(Boolean) }] });
    setDecision({ decision: "", rationale: "", owner: "", downstreamImpact: "", options: "" });
  }
  const resolved = packet.checklist.filter((item) => item.status === "resolved" || item.status === "not-applicable").length;
  const calibrationSummary = summarizeCalibration(packet);

  function updateCalibration(patch: Partial<QualityLabEngagementPacket["calibration"]>) {
    persist({ ...packet!, calibration: { ...packet!.calibration, ...patch } });
  }

  function updateMetricNote(metric: CalibrationMetricKey, patch: Partial<QualityLabEngagementPacket["calibration"]["metricNotes"][number]>) {
    updateCalibration({ metricNotes: packet!.calibration.metricNotes.map((item) => item.metric === metric ? { ...item, ...patch } : item) });
  }

  return <div className="min-h-screen bg-[#08111f] px-4 pb-24 pt-8 text-slate-100">
    <div className="mx-auto max-w-6xl">
      <div className="flex flex-wrap items-center justify-between gap-3"><Link href={`/quality-lab/projects/${project.id}`} className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft className="h-4 w-4" /> Back to blueprint</Link><Link href="/quality-lab/calibration" className="text-sm font-bold text-sky-300 hover:text-sky-200">Open learning review queue</Link></div>
      <header className="mt-6 rounded-3xl border border-teal-300/20 bg-gradient-to-br from-teal-300/10 to-slate-950 p-6 md:p-8">
        <div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-300">Service-assisted delivery · browser-local</p><h1 className="mt-2 text-3xl font-bold md:text-4xl">{project.name}</h1><p className="mt-3 text-sm text-slate-400">{packet.packetVersion} · {resolved}/{packet.checklist.length} review items resolved</p></div><div className="flex flex-col gap-2 sm:flex-row"><button onClick={() => { downloadCalibration(packet); analytics.engagementPacketDownloaded("calibration_csv", packet.checklist.length - resolved); }} className="inline-flex items-center justify-center gap-2 rounded-xl border border-teal-300/25 bg-teal-300/10 px-4 py-3 text-sm font-bold text-teal-200"><Download className="h-4 w-4" /> Export calibration CSV</button><button onClick={() => { downloadEngagement(packet); analytics.engagementPacketDownloaded("engagement_workspace", packet.checklist.length - resolved); }} className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-300 px-4 py-3 text-sm font-bold text-slate-950"><Download className="h-4 w-4" /> Export working packet</button></div></div>
        <div className="mt-5 flex gap-3 rounded-xl border border-amber-300/15 bg-amber-300/[0.05] p-4 text-xs leading-5 text-slate-400"><ShieldCheck className="h-5 w-5 shrink-0 text-amber-300" /> This workspace records review work; it does not approve the Blueprint. Controlled approval remains under the client quality system.</div>
      </header>

      <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.035] p-5">
        <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><h2 className="text-xl font-bold">Estimate-to-actual calibration</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-400">Capture what was observed, where it came from, why it differed and whether the learning stays project-specific or becomes a reviewed candidate for Atlas Intelligence.</p></div><span className={`w-fit rounded-full border px-3 py-1 text-[10px] font-bold uppercase ${calibrationSummary.reviewReady ? "border-teal-300/25 bg-teal-300/10 text-teal-200" : "border-amber-300/20 bg-amber-300/10 text-amber-200"}`}>{calibrationSummary.reviewReady ? "Review ready" : "Evidence incomplete"}</span></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{(Object.keys(packet.baseline) as CalibrationMetricKey[]).map((key) => { const item=packet.baseline[key]; const note=packet.calibration.metricNotes.find((row)=>row.metric===key)!; const band=varianceMagnitude(item.variancePercent); return <div key={key} className="rounded-xl border border-white/8 bg-black/15 p-3 text-xs text-slate-400"><p className="font-semibold text-slate-200">{baselineLabels[key]}</p><span className="mt-2 block">Estimate: {item.estimate.toLocaleString()}</span><label><span className="sr-only">{baselineLabels[key]} actual</span><input aria-label={`${baselineLabels[key]} actual`} type="number" min="0" step="any" value={item.actual ?? ""} onChange={(e) => setPacket(setEngagementActual(packet, key, e.target.value === "" ? null : Number(e.target.value)))} className={`${inputClass} mt-2`} placeholder="Actual" /></label><span className={`mt-2 block font-semibold ${band === "over-25" ? "text-red-200" : band === "10-to-25" ? "text-amber-200" : "text-teal-200"}`}>Variance: {item.variancePercent === null ? "open" : `${item.variancePercent}%`}</span><select aria-label={`${baselineLabels[key]} variance driver`} value={note.varianceDriver} onChange={(e)=>updateMetricNote(key,{varianceDriver:e.target.value as typeof note.varianceDriver})} className={`${inputClass} mt-3`}><option value="not-assessed">Driver not assessed</option><option value="input-quality">Input quality</option><option value="scope-change">Scope change</option><option value="rule-assumption">Rule assumption</option><option value="site-performance">Site performance</option><option value="market-price">Market price</option><option value="implementation-choice">Implementation choice</option><option value="mixed">Mixed drivers</option></select><textarea aria-label={`${baselineLabels[key]} actual basis`} value={note.actualBasis} onChange={(e)=>updateMetricNote(key,{actualBasis:e.target.value})} className={`${inputClass} mt-2`} rows={2} placeholder="Actual basis / calculation" /><textarea aria-label={`${baselineLabels[key]} calibration note`} value={note.reviewerNote} onChange={(e)=>updateMetricNote(key,{reviewerNote:e.target.value})} className={`${inputClass} mt-2`} rows={2} placeholder="Reviewer interpretation" /></div>; })}</div>
        <div className="mt-5 grid gap-4 rounded-xl border border-white/8 bg-black/15 p-4 md:grid-cols-2 lg:grid-cols-4">
          <label className="text-xs text-slate-400">Observed period start<input aria-label="Observed period start" type="date" value={packet.calibration.observedPeriodStart} onChange={(e)=>updateCalibration({observedPeriodStart:e.target.value})} className={`${inputClass} mt-1`} /></label>
          <label className="text-xs text-slate-400">Observed period end<input aria-label="Observed period end" type="date" value={packet.calibration.observedPeriodEnd} onChange={(e)=>updateCalibration({observedPeriodEnd:e.target.value})} className={`${inputClass} mt-1`} /></label>
          <label className="text-xs text-slate-400">Data owner<input aria-label="Calibration data owner" value={packet.calibration.dataOwner} onChange={(e)=>updateCalibration({dataOwner:e.target.value})} className={`${inputClass} mt-1`} placeholder="Role or controlled function" /></label>
          <label className="text-xs text-slate-400">Calibration status<select aria-label="Calibration status" value={packet.calibration.status} onChange={(e)=>updateCalibration({status:e.target.value as typeof packet.calibration.status, reviewedAt:e.target.value === "reviewed" ? new Date().toISOString() : null})} className={`${inputClass} mt-1`}><option value="draft">Draft</option><option value="observed">Observed</option><option value="review-ready">Review ready</option><option value="reviewed">Reviewed for learning</option></select></label>
          <label className="text-xs text-slate-400 md:col-span-2">Controlled evidence references (one per line)<textarea aria-label="Calibration evidence references" value={packet.calibration.evidenceRefs.join("\n")} onChange={(e)=>updateCalibration({evidenceRefs:e.target.value.split("\n").map((v)=>v.trim()).filter(Boolean)})} className={`${inputClass} mt-1`} rows={3} placeholder="Document ID, approved report, purchase record, time study…" /></label>
          <label className="text-xs text-slate-400">Learning disposition<select aria-label="Learning disposition" value={packet.calibration.learningDisposition} onChange={(e)=>updateCalibration({learningDisposition:e.target.value as typeof packet.calibration.learningDisposition})} className={`${inputClass} mt-1`}><option value="hold">Hold — evidence incomplete</option><option value="project-only">Project only</option><option value="candidate-rule-update">Candidate rule update</option><option value="candidate-benchmark">Candidate benchmark</option></select></label>
          <label className="text-xs text-slate-400">Reviewed by role<input aria-label="Calibration reviewed by role" value={packet.calibration.reviewedByRole} onChange={(e)=>updateCalibration({reviewedByRole:e.target.value})} className={`${inputClass} mt-1`} placeholder="Qualified reviewer role" /></label>
          <label className="text-xs text-slate-400 md:col-span-2">Applicable rule IDs (one per line)<textarea aria-label="Applicable calibration rule IDs" value={packet.calibration.applicableRuleIds.join("\n")} onChange={(e)=>updateCalibration({applicableRuleIds:e.target.value.split("\n").map((v)=>v.trim()).filter(Boolean)})} className={`${inputClass} mt-1`} rows={3} placeholder={project.blueprint.ruleTrace.slice(0,3).map((rule)=>rule.ruleId).join("\n")} /></label>
          <label className="text-xs text-slate-400 md:col-span-2">Disposition rationale<textarea aria-label="Calibration disposition rationale" value={packet.calibration.dispositionRationale} onChange={(e)=>updateCalibration({dispositionRationale:e.target.value})} className={`${inputClass} mt-1`} rows={3} placeholder="Why this learning should remain local or enter controlled rule/benchmark review" /></label>
        </div>
        <div className="mt-4 grid gap-2 text-xs sm:grid-cols-4"><span className="rounded-lg border border-white/8 p-3 text-slate-400"><strong className="block text-lg text-slate-100">{calibrationSummary.coveragePercent}%</strong>metrics observed</span><span className="rounded-lg border border-white/8 p-3 text-slate-400"><strong className="block text-lg text-slate-100">{calibrationSummary.materialVarianceCount}</strong>variances over 25%</span><span className="rounded-lg border border-white/8 p-3 text-slate-400"><strong className="block text-sm text-slate-100">{calibrationSummary.provenanceComplete ? "Complete" : "Open"}</strong>observation provenance</span><span className="rounded-lg border border-white/8 p-3 text-slate-400"><strong className="block text-sm text-slate-100">{calibrationSummary.notesComplete ? "Classified" : "Open"}</strong>variance drivers</span></div>
        <div className="mt-4 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><p className="text-[11px] leading-5 text-amber-200/70">{calibrationSummary.notice}</p><Link href="/blog/how-to-validate-a-quality-lab-domain-pack" className="shrink-0 text-[11px] font-bold text-teal-300">Validation framework</Link></div>
      </section>

      {revisions.length > 0 && <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.035] p-5"><h2 className="text-xl font-bold">Reviewed-project history</h2><p className="mt-1 text-xs text-slate-400">Immutable server revisions; comparison is decision-support only.</p><div className="mt-3 flex flex-wrap gap-2">{revisions.map((revision) => <span key={revision.revisionNumber} className="rounded-lg border border-white/10 bg-black/15 px-3 py-2 text-xs text-slate-300">Revision {revision.revisionNumber} · {revision.blockingOpenCount} blocking</span>)}</div></section>}

      <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-center gap-3"><ClipboardCheck className="h-5 w-5 text-teal-300"/><h2 className="text-xl font-bold">Evidence and review checklist</h2></div><div className="mt-4 space-y-3">{packet.checklist.map((item) => <article key={item.id} className="rounded-xl border border-white/8 bg-black/15 p-4"><div className="grid gap-3 md:grid-cols-[1fr_180px]"><div><p className="text-sm font-bold">{item.question}</p><p className="mt-2 text-xs leading-5 text-slate-400"><strong>Evidence:</strong> {item.requiredEvidence}</p><p className="mt-1 text-[11px] text-slate-500">Owner: {item.ownerRole}</p></div><select aria-label={`Status for ${item.question}`} value={item.status} onChange={(e) => persist({ ...packet, checklist: packet.checklist.map((row) => row.id === item.id ? { ...row, status: e.target.value as typeof row.status } : row) })} className={inputClass}><option value="open">Open</option><option value="in-review">In review</option><option value="resolved">Resolved</option><option value="not-applicable">Not applicable</option></select></div><textarea aria-label={`Reviewer note for ${item.question}`} value={item.reviewerNote} onChange={(e) => persist({ ...packet, checklist: packet.checklist.map((row) => row.id === item.id ? { ...row, reviewerNote: e.target.value } : row) })} className={`${inputClass} mt-3`} rows={2} placeholder="Reviewer note and evidence reference" /></article>)}</div></section>

      {packet.methodEvidenceMatrix.length > 0 && <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-center gap-3"><ClipboardCheck className="h-5 w-5 text-teal-300"/><div><h2 className="text-xl font-bold">Method evidence matrix</h2><p className="mt-1 text-xs leading-5 text-slate-400">A review matrix, not a claim that the displayed method is approved for this site.</p></div></div><div className="mt-4 space-y-3">{packet.methodEvidenceMatrix.map((item) => <article key={item.id} className="rounded-xl border border-white/8 bg-black/15 p-4"><div className="grid gap-3 md:grid-cols-[1fr_190px]"><div><p className="text-sm font-bold">{item.productName} · {item.methodName}</p><p className="mt-1 text-[11px] text-slate-500">{item.market} · {item.requirementType.replaceAll("-", " ")}</p><p className="mt-2 text-xs leading-5 text-slate-400"><strong>Evidence references:</strong> {item.evidenceIds.join(" · ")}</p><p className="mt-2 text-xs leading-5 text-amber-200/80"><strong>Verification:</strong> {item.verificationRequirement}</p></div><select aria-label={`Method evidence status for ${item.methodName}`} value={item.status} onChange={(e) => persist({ ...packet, methodEvidenceMatrix: packet.methodEvidenceMatrix.map((row) => row.id === item.id ? { ...row, status: e.target.value as typeof row.status } : row) })} className={inputClass}><option value="draft">Draft</option><option value="needs-site-evidence">Needs site evidence</option><option value="ready-for-qualified-review">Ready for qualified review</option></select></div><textarea aria-label={`Method evidence reviewer note for ${item.methodName}`} value={item.reviewerNote} onChange={(e) => persist({ ...packet, methodEvidenceMatrix: packet.methodEvidenceMatrix.map((row) => row.id === item.id ? { ...row, reviewerNote: e.target.value } : row) })} className={`${inputClass} mt-3`} rows={2} placeholder="Controlled document reference, reviewer note, or gap" /></article>)}</div></section>}

      {packet.ursBasis.length > 0 && <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div><h2 className="text-xl font-bold">Vendor-neutral URS basis</h2><p className="mt-1 text-xs leading-5 text-slate-400">Functional requirements for qualified drafting; this is not an issued URS or RFQ package.</p></div><div className="mt-4 grid gap-3 md:grid-cols-2">{packet.ursBasis.map((item) => <article key={item.id} className="rounded-xl border border-white/8 bg-black/15 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{item.equipmentName}</p><p className="mt-1 text-[11px] text-slate-500">{item.equipmentCategory}</p></div><span className="rounded-full border border-white/10 px-2 py-1 text-[9px] font-bold uppercase text-slate-400">{item.status.replaceAll("-", " ")}</span></div><p className="mt-3 text-xs leading-5 text-slate-300"><strong>Functional basis:</strong> {item.functionalRequirement}</p><p className="mt-3 text-xs leading-5 text-amber-200/80"><strong>Qualification impact:</strong> {item.qualificationImpact}</p>{item.relatedMethodRequirementIds.length > 0 && <p className="mt-2 break-words font-mono text-[10px] text-sky-200/70">Method links: {item.relatedMethodRequirementIds.join(" · ")}</p>}{item.evidenceIds.length > 0 && <p className="mt-2 break-words font-mono text-[10px] text-sky-200/70">Evidence: {item.evidenceIds.join(" · ")}</p>}</article>)}</div></section>}

      <div className="mt-5 grid gap-5 lg:grid-cols-2">
        <form onSubmit={addCorrection} className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><h2 className="text-xl font-bold">Correction log</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{([['fieldOrRuleId','Field or rule ID'],['previousValue','Previous value'],['correctedValue','Corrected value'],['evidenceRef','Evidence reference'],['reviewerRole','Reviewer role']] as const).map(([key,label])=><label key={key} className="text-xs text-slate-400">{label}<input required value={correction[key]} onChange={(e)=>setCorrection({...correction,[key]:e.target.value})} className={`${inputClass} mt-1`}/></label>)}</div><label className="mt-3 block text-xs text-slate-400">Rationale<textarea required value={correction.rationale} onChange={(e)=>setCorrection({...correction,rationale:e.target.value})} className={`${inputClass} mt-1`} rows={3}/></label><button className="mt-4 inline-flex items-center gap-2 rounded-lg bg-white/10 px-4 py-2 text-sm font-bold"><Plus className="h-4 w-4"/> Add correction</button><p className="mt-3 text-xs text-slate-500">{packet.corrections.length} corrections recorded</p></form>
        <form onSubmit={addDecision} className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><h2 className="text-xl font-bold">Decision log</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{([['decision','Decision'],['owner','Decision owner'],['downstreamImpact','Downstream impact']] as const).map(([key,label])=><label key={key} className="text-xs text-slate-400">{label}<input required value={decision[key]} onChange={(e)=>setDecision({...decision,[key]:e.target.value})} className={`${inputClass} mt-1`}/></label>)}</div><label className="mt-3 block text-xs text-slate-400">Options considered (one per line)<textarea required value={decision.options} onChange={(e)=>setDecision({...decision,options:e.target.value})} className={`${inputClass} mt-1`} rows={2}/></label><label className="mt-3 block text-xs text-slate-400">Rationale<textarea required value={decision.rationale} onChange={(e)=>setDecision({...decision,rationale:e.target.value})} className={`${inputClass} mt-1`} rows={3}/></label><button className="mt-4 inline-flex items-center gap-2 rounded-lg bg-white/10 px-4 py-2 text-sm font-bold"><Plus className="h-4 w-4"/> Add decision</button><p className="mt-3 flex items-center gap-2 text-xs text-slate-500"><CheckCircle2 className="h-3.5 w-3.5"/>{packet.decisions.length} decisions recorded</p></form>
      </div>
    </div>
  </div>;
}
