import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { AlertTriangle, ArrowLeft, ArrowRight, CheckCircle2, Cog, Download, FlaskConical, Gauge, Info, ShieldAlert, ShieldCheck, Wrench } from "lucide-react";
import { defaultEquipmentResilienceInput, evaluateEquipmentResilience, type EquipmentResilienceInput, type EquipmentResilienceResource, type EquipmentResilienceStatus } from "@shared/quality-lab-equipment-resilience";
import type { QualityLabProject } from "@shared/quality-lab";
import { listQualityLabProjects } from "@/lib/quality-lab-projects";
import { useSEO } from "@/hooks/use-seo";
import { analytics } from "@/hooks/use-analytics";

const number = new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 });
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 1 });

function initialProjectId() { return typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("project") ?? ""; }

function statusStyle(status: EquipmentResilienceStatus | "not-applicable") {
  if (["geometry-fail", "normal-capacity-fail", "recovery-fail", "single-point-failure"].includes(status)) return { label: status.replaceAll("-", " "), icon: ShieldAlert, className: "border-red-300/20 bg-red-300/[0.07] text-red-100" };
  if (status === "recoverable") return { label: "recoverable backlog", icon: AlertTriangle, className: "border-amber-300/20 bg-amber-300/[0.07] text-amber-100" };
  if (status === "resilient") return { label: "one-unit-loss resilient", icon: CheckCircle2, className: "border-teal-300/20 bg-teal-300/[0.07] text-teal-100" };
  return { label: "not applicable", icon: Info, className: "border-sky-300/20 bg-sky-300/[0.07] text-sky-100" };
}

export default function QualityLabEquipmentResiliencePage() {
  useSEO({ title: "Equipment Configuration & Resilience", description: "Test Quality Lab equipment load geometry, normal capacity, one-unit failure continuity, backlog recovery and N+1 planning gaps." });
  const [projects] = useState<QualityLabProject[]>(() => listQualityLabProjects());
  const [projectId, setProjectId] = useState(() => initialProjectId() || projects[0]?.id || "");
  const project = projects.find((item) => item.id === projectId);
  const [input, setInput] = useState<EquipmentResilienceInput | null>(() => project ? defaultEquipmentResilienceInput(project) : null);

  useEffect(() => { if (project) setInput(defaultEquipmentResilienceInput(project)); }, [project?.id]);
  const result = useMemo(() => project && input ? evaluateEquipmentResilience(project, input) : null, [project, input]);
  useEffect(() => {
    if (!result) return;
    const url = new URL(window.location.href); url.searchParams.set("project", result.project.id); window.history.replaceState({}, "", url);
    analytics.equipmentResilienceEvaluated(result.project.id, result.project.demandHorizon, result.overallStatus, result.summary.nPlusOneGapUnits);
  }, [result?.project.id, result?.project.demandHorizon, result?.overallStatus, result?.summary.nPlusOneGapUnits]);

  function patch<K extends keyof EquipmentResilienceInput>(key: K, value: EquipmentResilienceInput[K]) { setInput((current) => current ? { ...current, [key]: value } : current); }
  function patchResource(resourceId: string, key: string, value: number) { setInput((current) => current ? { ...current, resources: current.resources.map((resource) => resource.resourceId === resourceId ? { ...resource, [key]: value } : resource) } : current); }
  function exportResult() {
    if (!result) return;
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "atlas-equipment-resilience-trace.json"; anchor.click(); URL.revokeObjectURL(url);
    analytics.equipmentResilienceExported(result.overallStatus, result.summary.nPlusOneGapUnits);
  }

  return <div className="min-h-screen bg-[#07111f] px-4 pb-24 pt-6 text-slate-100 md:pt-10"><div className="mx-auto max-w-7xl">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><Link href="/quality-lab/projects" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4" /> Quality lab projects</Link>{result && <button onClick={exportResult} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-bold text-slate-200 hover:border-teal-300/30 hover:text-white"><Download className="h-4 w-4" /> Export resilience trace</button>}</div>
    <header className="rounded-3xl border border-emerald-300/20 bg-gradient-to-br from-emerald-300/10 via-white/[0.035] to-sky-300/[0.04] p-6 md:p-8"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-300/10 text-emerald-200"><ShieldCheck className="h-5 w-5" /></div><p className="mt-5 text-xs font-bold uppercase tracking-[0.18em] text-emerald-300">Atlas Intelligence</p><h1 className="mt-2 text-3xl font-bold md:text-5xl">Equipment Configuration & Resilience</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-400">Test whether each method-linked resource fits its largest load, carries peak demand in normal operation, and survives one-unit loss without an unrecoverable backlog.</p></header>

    {projects.length === 0 ? <section className="mt-6 rounded-3xl border border-dashed border-white/15 bg-white/[0.025] px-6 py-16 text-center"><FlaskConical className="mx-auto h-8 w-8 text-slate-500" /><h2 className="mt-5 text-xl font-bold">A method-linked Blueprint is required</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">Compile an in-house non-sterile product profile so Atlas can connect method demand to critical resources.</p><Link href="/quality-lab/planner" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-teal-300 px-5 py-3 text-sm font-bold text-slate-950">Build a blueprint <ArrowRight className="h-4 w-4" /></Link></section> : result && input ? <div className="mt-6 space-y-6">
      <section className="grid gap-4 rounded-2xl border border-white/10 bg-white/[0.035] p-5 md:grid-cols-2 lg:grid-cols-5">
        <label className="lg:col-span-2"><FieldLabel>Blueprint project</FieldLabel><select value={projectId} onChange={(event) => setProjectId(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-3 text-sm font-semibold text-white">{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
        <label><FieldLabel>Demand horizon</FieldLabel><select value={input.demandHorizon} onChange={(event) => patch("demandHorizon", event.target.value as "current" | "future")} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-3 text-sm font-semibold text-white"><option value="current">Current</option><option value="future">Future</option></select></label>
        <NumberField label="Peak factor" value={input.demandPeakFactor} min={1} max={3} step={0.1} suffix="×" onChange={(value) => patch("demandPeakFactor", value)} />
        <NumberField label="Failure duration" value={input.singleFailureDurationDays} min={0.5} max={90} step={0.5} suffix="days" onChange={(value) => patch("singleFailureDurationDays", value)} />
        <NumberField label="Max recovery" value={input.maximumRecoveryDays} min={0} max={60} step={0.5} suffix="days" onChange={(value) => patch("maximumRecoveryDays", value)} />
      </section>

      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><SummaryCard label="Overall screen" value={statusStyle(result.overallStatus).label} /><SummaryCard label="Resilient resources" value={`${result.summary.resilientCount}/${result.resources.length}`} /><SummaryCard label="Single points" value={String(result.summary.singlePointCount)} /><SummaryCard label="N+1 unit gap" value={String(result.summary.nPlusOneGapUnits)} /><SummaryCard label="Gap CAPEX band" value={`${money.format(result.summary.incrementalCapexLowUsd)}–${money.format(result.summary.incrementalCapexHighUsd)}`} /></section>

      {result.resources.length ? <section><SectionHeading icon={Cog} title="Configuration stress test" description="Edit usable geometry and availability from vendor/site evidence. Installed units are the selected Blueprint horizon quantity." /><div className="mt-4 grid gap-5 lg:grid-cols-2">{result.resources.map((resource) => { const configuration = input.resources.find((item) => item.resourceId === resource.resourceId)!; return <ResourceCard key={resource.resourceId} resource={resource} configuration={configuration} onChange={(key, value) => patchResource(resource.resourceId, key, value)} />; })}</div></section> : <div className="rounded-2xl border border-amber-300/20 bg-amber-300/[0.06] p-5 text-sm text-amber-100">No method-derived equipment demand is available. Confirm an in-house product method profile and recompile the Blueprint.</div>}

      <section className="grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><SectionHeading icon={Gauge} title="Decision signals" description="Configuration and continuity triggers generated from the selected assumptions." /><div className="mt-4 space-y-3">{result.signals.map((signal) => { const style = signal.severity === "critical" ? statusStyle("normal-capacity-fail") : signal.severity === "positive" ? statusStyle("resilient") : statusStyle("recoverable"); const Icon = style.icon; return <article key={signal.id} className={`rounded-xl border p-4 ${style.className}`}><div className="flex gap-3"><Icon className="mt-0.5 h-4 w-4 shrink-0" /><div><h3 className="text-sm font-bold">{signal.title}</h3><p className="mt-1 text-xs leading-6 opacity-75">{signal.description}</p></div></div></article>; })}</div></div><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><SectionHeading icon={Wrench} title="Evidence required before URS" description="The configuration is only as credible as the load, cycle and failure evidence behind it." /><div className="mt-4 space-y-4">{result.resources.map((resource) => <article key={resource.resourceId} className="rounded-xl border border-white/8 bg-slate-950/30 p-4"><h3 className="text-sm font-bold text-slate-200">{resource.resourceName}</h3><ul className="mt-2 space-y-1 text-xs leading-5 text-slate-500">{resource.evidenceNeeded.map((item) => <li key={item}>• {item}</li>)}</ul></article>)}</div></div></section>

      <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><SectionHeading icon={Info} title="Assumption register" description="Inputs that require site or engineering confirmation." /><div className="mt-4 space-y-3">{result.assumptions.map((item) => <article key={item.id} className="rounded-xl border border-white/8 bg-slate-950/30 p-4"><p className="text-sm font-semibold text-slate-200">{item.value}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.evidenceNeeded}</p><span className="mt-2 inline-block text-[9px] font-bold uppercase tracking-wider text-amber-300">{item.confidence}</span></article>)}</div></div><div className="rounded-2xl border border-emerald-300/15 bg-emerald-300/[0.04] p-5"><SectionHeading icon={ShieldCheck} title="Rule trace" description={`${result.ruleTrace[0].ruleId} · ${result.ruleTrace[0].ruleVersion}`} /><p className="mt-4 text-xs leading-6 text-emerald-100/70">{result.ruleTrace[0].role}</p><p className="mt-3 text-xs leading-6 text-slate-500">{result.ruleTrace[0].limitation}</p></div></section>
      <div className="rounded-2xl border border-sky-300/15 bg-sky-300/[0.05] p-5 text-xs leading-6 text-sky-100"><Info className="mr-2 inline h-4 w-4 text-sky-300" />{result.boundary}</div>
    </div> : null}
  </div></div>;
}

function ResourceCard({ resource, configuration, onChange }: { resource: EquipmentResilienceResource; configuration: EquipmentResilienceInput["resources"][number]; onChange: (key: string, value: number) => void }) {
  const style = statusStyle(resource.status); const Icon = style.icon;
  return <article className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-white">{resource.resourceName}</h3><p className="mt-1 text-xs text-slate-500">{resource.monthlyDemand} {resource.unit}/month · peak {resource.peakDailyDemand}/day</p></div><span className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[9px] font-bold uppercase tracking-wider ${style.className}`}><Icon className="h-3 w-3" /> {style.label}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><NumberField label="Installed units" value={configuration.installedUnits} min={0} max={100} step={1} onChange={(value) => onChange("installedUnits", Math.round(value))} /><NumberField label="Nominal capacity" value={configuration.capacityPerUnitPerDay} min={0.1} max={100000} step={1} suffix={`${resource.unit}/unit-day`} onChange={(value) => onChange("capacityPerUnitPerDay", value)} /><NumberField label="Usable capacity" value={configuration.usableCapacityPercent} min={1} max={100} step={1} suffix="%" onChange={(value) => onChange("usableCapacityPercent", value)} /><NumberField label="Availability" value={configuration.availabilityPercent} min={1} max={100} step={1} suffix="%" onChange={(value) => onChange("availabilityPercent", value)} /><NumberField label="Operating days" value={configuration.operatingDaysPerMonth} min={1} max={31} step={1} suffix="/month" onChange={(value) => onChange("operatingDaysPerMonth", value)} /><NumberField label="Largest concurrent load" value={configuration.largestConcurrentLoad} min={0} max={1000000} step={1} suffix={resource.unit} onChange={(value) => onChange("largestConcurrentLoad", value)} /></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><Metric label="Normal use" value={`${resource.normalUtilizationPercent}%`} /><Metric label="After 1-unit loss" value={resource.failureUtilizationPercent === null ? "No capacity" : `${resource.failureUtilizationPercent}%`} /><Metric label="Recovery" value={resource.modeledRecoveryDays === null ? "Not recoverable" : `${resource.modeledRecoveryDays} days`} /><Metric label="N+1 target" value={`${resource.minimumUnitsNPlusOne} units`} /></div></article>;
}

function SummaryCard({ label, value }: { label: string; value: string }) { return <article className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><p className="text-xs font-semibold text-slate-500">{label}</p><strong className="mt-3 block text-lg capitalize text-emerald-200">{value}</strong></article>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/8 bg-slate-950/30 p-3"><p className="text-[9px] uppercase tracking-wider text-slate-600">{label}</p><strong className="mt-1 block text-slate-200">{value}</strong></div>; }
function FieldLabel({ children }: { children: React.ReactNode }) { return <span className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">{children}</span>; }
function NumberField({ label, value, onChange, min, max, step, suffix }: { label: string; value: number; onChange: (value: number) => void; min: number; max: number; step: number; suffix?: string }) { return <label><FieldLabel>{label}</FieldLabel><div className="mt-2 flex h-11 items-center rounded-xl border border-white/10 bg-slate-950 px-3 focus-within:border-emerald-300/40"><input aria-label={label} type="number" value={value} min={min} max={max} step={step} onChange={(event) => onChange(Math.min(max, Math.max(min, Number(event.target.value) || 0)))} className="min-w-0 flex-1 bg-transparent text-sm font-semibold text-white outline-none" />{suffix && <span className="ml-2 text-[10px] text-slate-600">{suffix}</span>}</div></label>; }
function SectionHeading({ icon: Icon, title, description }: { icon: typeof Gauge; title: string; description: string }) { return <div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-emerald-300/10 text-emerald-300"><Icon className="h-4 w-4" /></div><div><h2 className="text-lg font-bold text-white">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div></div>; }
