import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { AlertTriangle, ArrowLeft, ArrowRight, CheckCircle2, ClipboardCheck, Download, FlaskConical, Gauge, Info, ShieldAlert, Users } from "lucide-react";
import { defaultNonRoutineLoadInput, evaluateNonRoutineLoad, type NonRoutineEventInput, type NonRoutineLoadInput, type NonRoutineLoadStatus, type RoleCapacityResult } from "@shared/quality-lab-non-routine";
import type { QualityLabProject } from "@shared/quality-lab";
import { listQualityLabProjects } from "@/lib/quality-lab-projects";
import { useSEO } from "@/hooks/use-seo";
import { analytics } from "@/hooks/use-analytics";

const number = new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 });
function initialProjectId() { return typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("project") ?? ""; }
function statusStyle(status: NonRoutineLoadStatus) {
  if (status === "capacity-gap") return { label: "capacity gap", icon: ShieldAlert, className: "border-red-300/20 bg-red-300/[0.07] text-red-100" };
  if (status === "tight") return { label: "tight capacity", icon: AlertTriangle, className: "border-amber-300/20 bg-amber-300/[0.07] text-amber-100" };
  return { label: "concept pass", icon: CheckCircle2, className: "border-teal-300/20 bg-teal-300/[0.07] text-teal-100" };
}

export default function QualityLabNonRoutineLoadPage() {
  useSEO({ title: "Investigation & Non-routine Load", description: "Add deviations, OOS/OOT, contamination, repeats, qualification and method lifecycle work to routine Quality Lab staffing demand." });
  const [projects] = useState<QualityLabProject[]>(() => listQualityLabProjects());
  const [projectId, setProjectId] = useState(() => initialProjectId() || projects[0]?.id || "");
  const project = projects.find((item) => item.id === projectId);
  const [input, setInput] = useState<NonRoutineLoadInput | null>(() => project ? defaultNonRoutineLoadInput(project) : null);
  useEffect(() => { if (project) setInput(defaultNonRoutineLoadInput(project)); }, [project?.id]);
  const result = useMemo(() => project && input ? evaluateNonRoutineLoad(project, input) : null, [project, input]);
  useEffect(() => { if (!result) return; const url = new URL(window.location.href); url.searchParams.set("project", result.project.id); window.history.replaceState({}, "", url); analytics.nonRoutineLoadEvaluated(result.project.id, result.project.demandHorizon, result.overallStatus, result.totalNonRoutineHours); }, [result?.project.id, result?.project.demandHorizon, result?.overallStatus, result?.totalNonRoutineHours]);
  function patch<K extends keyof NonRoutineLoadInput>(key: K, value: NonRoutineLoadInput[K]) { setInput((current) => current ? { ...current, [key]: value } : current); }
  function patchEvent(id: NonRoutineEventInput["id"], key: keyof NonRoutineEventInput, value: number | string) { setInput((current) => current ? { ...current, events: current.events.map((event) => event.id === id ? { ...event, [key]: value } : event) } : current); }
  function exportResult() { if (!result) return; const blob = new Blob([JSON.stringify(result, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "atlas-non-routine-load-trace.json"; anchor.click(); URL.revokeObjectURL(url); analytics.nonRoutineLoadExported(result.overallStatus, result.evidenceSummary.observedCount); }

  return <div className="min-h-screen bg-[#07111f] px-4 pb-24 pt-6 text-slate-100 md:pt-10"><div className="mx-auto max-w-7xl">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><Link href="/quality-lab/projects" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4" /> Quality lab projects</Link>{result && <button onClick={exportResult} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-bold text-slate-200 hover:border-teal-300/30 hover:text-white"><Download className="h-4 w-4" /> Export workload trace</button>}</div>
    <header className="rounded-3xl border border-amber-300/20 bg-gradient-to-br from-amber-300/10 via-white/[0.035] to-red-300/[0.04] p-6 md:p-8"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-amber-300/10 text-amber-200"><AlertTriangle className="h-5 w-5" /></div><p className="mt-5 text-xs font-bold uppercase tracking-[0.18em] text-amber-300">Atlas Intelligence</p><h1 className="mt-2 text-3xl font-bold md:text-5xl">Investigation & Non-routine Load</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-400">Convert exception events into analyst and reviewer hours, expose how much Blueprint resilience reserve they consume, and detect staffing that only appears sufficient because non-routine work was omitted.</p></header>
    {projects.length === 0 ? <section className="mt-6 rounded-3xl border border-dashed border-white/15 bg-white/[0.025] px-6 py-16 text-center"><FlaskConical className="mx-auto h-8 w-8 text-slate-500" /><h2 className="mt-5 text-xl font-bold">A compiled Blueprint is required</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">Build a project so Atlas can combine routine workload with exception and lifecycle demand.</p><Link href="/quality-lab/planner" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-teal-300 px-5 py-3 text-sm font-bold text-slate-950">Build a blueprint <ArrowRight className="h-4 w-4" /></Link></section> : result && input ? <div className="mt-6 space-y-6">
      <section className="grid gap-4 rounded-2xl border border-white/10 bg-white/[0.035] p-5 sm:grid-cols-2 lg:grid-cols-4"><label className="sm:col-span-2"><FieldLabel>Blueprint project</FieldLabel><select value={projectId} onChange={(event) => setProjectId(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-3 text-sm font-semibold text-white">{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><FieldLabel>Demand horizon</FieldLabel><select value={input.demandHorizon} onChange={(event) => patch("demandHorizon", event.target.value as "current" | "future")} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-3 text-sm font-semibold text-white"><option value="current">Current</option><option value="future">Future</option></select></label><NumberField label="Absence & leave" value={input.absenceAndLeavePercent} min={0} max={50} step={1} suffix="%" onChange={(value) => patch("absenceAndLeavePercent", value)} /><NumberField label="Available analysts" value={input.availableAnalystFte} min={0.1} max={500} step={0.1} suffix="FTE" onChange={(value) => patch("availableAnalystFte", value)} /><NumberField label="Available reviewers" value={input.availableReviewerFte} min={0.1} max={100} step={0.1} suffix="FTE" onChange={(value) => patch("availableReviewerFte", value)} /><NumberField label="Routine review" value={input.routineReviewMinutesPerUnit} min={0} max={240} step={1} suffix="min/unit" onChange={(value) => patch("routineReviewMinutesPerUnit", value)} /><NumberField label="Weekly handover" value={input.weeklyHandoverHours} min={0} max={500} step={0.5} suffix="analyst h" onChange={(value) => patch("weeklyHandoverHours", value)} /></section>
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><SummaryCard label="Overall screen" value={statusStyle(result.overallStatus).label} /><SummaryCard label="Non-routine load" value={`${number.format(result.totalNonRoutineHours)} h/month`} /><SummaryCard label="Share of total work" value={`${result.nonRoutineSharePercent}%`} /><SummaryCard label="Analyst exception demand" value={`${result.nonRoutineAnalystFte} FTE`} /><SummaryCard label="Reserve coverage" value={result.reserveCoveragePercent === null ? "No exception load" : `${result.reserveCoveragePercent}%`} /></section>
      <section><SectionHeading icon={ClipboardCheck} title="Exception event model" description="Defaults are illustrative stress inputs, not Atlas benchmarks. Replace them with non-duplicated site event and role-hour evidence." /><div className="mt-4 grid gap-4 lg:grid-cols-2">{result.events.map((event) => <article key={event.id} className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-white">{event.label}</h3><p className="mt-1 text-xs text-slate-500">{event.totalMonthlyHours} total role-hours/month</p></div><span className="rounded-full border border-amber-300/15 bg-amber-300/[0.06] px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-amber-200">{event.evidenceBasis.replaceAll("-", " ")}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><NumberField label="Events / month" value={event.eventsPerMonth} min={0} max={10000} step={0.25} onChange={(value) => patchEvent(event.id, "eventsPerMonth", value)} /><NumberField label="Analyst h / event" value={event.analystHoursPerEvent} min={0} max={10000} step={0.5} onChange={(value) => patchEvent(event.id, "analystHoursPerEvent", value)} /><NumberField label="Reviewer h / event" value={event.reviewerHoursPerEvent} min={0} max={10000} step={0.5} onChange={(value) => patchEvent(event.id, "reviewerHoursPerEvent", value)} /></div><label className="mt-3 block"><FieldLabel>Evidence basis</FieldLabel><select aria-label={`${event.label} evidence basis`} value={event.evidenceBasis} onChange={(change) => patchEvent(event.id, "evidenceBasis", change.target.value)} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-slate-950 px-3 text-xs font-semibold text-white"><option value="illustrative-stress">Illustrative stress input</option><option value="user-supplied-estimate">User-supplied estimate</option><option value="observed-site-data">Observed site data — reference required</option></select></label></article>)}</div></section>
      <section className="grid gap-5 lg:grid-cols-2"><RoleCard result={result.analyst} /><RoleCard result={result.reviewer} /></section>
      <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><SectionHeading icon={Gauge} title="Decision signals" description="Capacity and evidence triggers generated from the selected event model." /><div className="mt-4 space-y-3">{result.signals.map((signal) => { const style = signal.severity === "critical" ? statusStyle("capacity-gap") : signal.severity === "positive" ? statusStyle("concept-pass") : statusStyle("tight"); const Icon = style.icon; return <article key={signal.id} className={`rounded-xl border p-4 ${style.className}`}><div className="flex gap-3"><Icon className="mt-0.5 h-4 w-4 shrink-0" /><div><h3 className="text-sm font-bold">{signal.title}</h3><p className="mt-1 text-xs leading-6 opacity-75">{signal.description}</p></div></div></article>; })}</div></div><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><SectionHeading icon={Users} title="Evidence collection plan" description={`${result.evidenceSummary.observedCount}/6 event types marked as observed; Atlas does not store the supporting records here.`} /><div className="mt-4 space-y-3">{result.events.map((event) => <article key={event.id} className="rounded-xl border border-white/8 bg-slate-950/30 p-4"><h3 className="text-sm font-bold text-slate-200">{event.label}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{event.evidenceNeeded}</p></article>)}</div></div></section>
      <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><SectionHeading icon={Info} title="Assumption register" description="Capacity inputs that still require controlled evidence." /><div className="mt-4 space-y-3">{result.assumptions.map((item) => <article key={item.id} className="rounded-xl border border-white/8 bg-slate-950/30 p-4"><p className="text-sm font-semibold text-slate-200">{item.value}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.evidenceNeeded}</p></article>)}</div></div><div className="rounded-2xl border border-amber-300/15 bg-amber-300/[0.04] p-5"><SectionHeading icon={AlertTriangle} title="Rule trace" description={`${result.ruleTrace[0].ruleId} · ${result.ruleTrace[0].ruleVersion}`} /><p className="mt-4 text-xs leading-6 text-amber-100/70">{result.ruleTrace[0].role}</p><p className="mt-3 text-xs leading-6 text-slate-500">{result.ruleTrace[0].limitation}</p></div></section>
      <div className="rounded-2xl border border-sky-300/15 bg-sky-300/[0.05] p-5 text-xs leading-6 text-sky-100"><Info className="mr-2 inline h-4 w-4 text-sky-300" />{result.boundary}</div>
    </div> : null}
  </div></div>;
}

function RoleCard({ result }: { result: RoleCapacityResult }) { const style = statusStyle(result.status); const Icon = style.icon; return <article className={`rounded-2xl border p-5 ${style.className}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.15em] opacity-60">{result.role} capacity</p><h2 className="mt-2 text-2xl font-bold">{result.utilizationPercent}% utilized</h2></div><Icon className="h-5 w-5" /></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Routine" value={`${result.routineHours} h`} /><Metric label="Non-routine" value={`${result.nonRoutineHours} h`} /><Metric label="Required" value={`${result.requiredFte} FTE`} /><Metric label="FTE gap" value={`${result.fteGap}`} /></div><p className="mt-3 text-xs opacity-60">{result.totalDemandHours} demand hours / {result.absenceAdjustedCapacityHours} absence-adjusted capacity hours</p></article>; }
function SummaryCard({ label, value }: { label: string; value: string }) { return <article className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><p className="text-xs font-semibold text-slate-500">{label}</p><strong className="mt-3 block text-lg capitalize text-amber-200">{value}</strong></article>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-current/10 bg-black/10 p-3"><p className="text-[9px] uppercase tracking-wider opacity-50">{label}</p><strong className="mt-1 block">{value}</strong></div>; }
function FieldLabel({ children }: { children: React.ReactNode }) { return <span className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">{children}</span>; }
function NumberField({ label, value, onChange, min, max, step, suffix }: { label: string; value: number; onChange: (value: number) => void; min: number; max: number; step: number; suffix?: string }) { return <label><FieldLabel>{label}</FieldLabel><div className="mt-2 flex h-11 items-center rounded-xl border border-white/10 bg-slate-950 px-3 focus-within:border-amber-300/40"><input aria-label={label} type="number" value={value} min={min} max={max} step={step} onChange={(event) => onChange(Math.min(max, Math.max(min, Number(event.target.value) || 0)))} className="min-w-0 flex-1 bg-transparent text-sm font-semibold text-white outline-none" />{suffix && <span className="ml-2 text-[10px] text-slate-600">{suffix}</span>}</div></label>; }
function SectionHeading({ icon: Icon, title, description }: { icon: typeof Gauge; title: string; description: string }) { return <div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-amber-300/10 text-amber-300"><Icon className="h-4 w-4" /></div><div><h2 className="text-lg font-bold text-white">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div></div>; }
