import { defineLearningFlow } from "../decision-package-learning-types.js";

export const BIOPHARMA_DECISION_PACKAGE_LEARNING_FLOWS = [
  defineLearningFlow({
    packageId: "biopharma-cell-materials-upstream",
    learningObjectives: [
      "Trace cell-substrate identity, bank history, raw and ancillary materials, single-use assemblies and upstream operations into one evidence chain.",
      "Separate material or process hypotheses from demonstrated effects on product quality and process performance.",
      "Frame the evidence and reviewers required before a bank, material, supplier or upstream change decision.",
    ],
    knowledgeUnits: [
      { title: "Cell substrate and bank lifecycle", explanation: "Cell-line provenance, construct history, clone selection, bank hierarchy, characterization, stability and production-age evidence establish what biological starting system is actually being used.", decisionUse: "Use the chain to identify which identity, history, stability and comparability records must support use or change of a bank." },
      { title: "Material function and variability", explanation: "Media, feeds, gases, resins, filters, supplements and single-use contact materials can affect growth, productivity, impurity burden and product attributes through different mechanisms.", decisionUse: "Map each input to intended function, variability evidence, supplier controls and the product/process questions it could influence." },
      { title: "Upstream control strategy", explanation: "Process understanding connects inoculum train, culture environment, monitoring, harvest timing and deviations to performance and downstream burden without treating one observed correlation as causality.", decisionUse: "Place monitoring and controls where they answer a named decision and identify what remains product- and platform-specific." },
    ],
    workflowPhases: [
      { id: "scope", title: "Freeze the biological and decision boundary", objective: "Define the exact cell substrate, bank tier, process version, facility/site, scale and decision being supported.", activities: ["Record lineage and bank-use scope.", "Name the change, deviation or development question.", "List accountable process, analytical, quality and regulatory reviewers."], evidenceToCapture: ["Approved lineage and bank records", "Process version and scale", "Decision owner and due date"], decisionGate: "Do not continue if the cell/bank/process version or intended decision is ambiguous." },
      { id: "map", title: "Build the cell–material–process map", objective: "Connect cell substrate, materials, suppliers and upstream operations to intended functions and affected attributes.", activities: ["Map bank and seed-train handoffs.", "Classify material criticality as a hypothesis with rationale.", "Connect upstream signals to harvest and downstream inputs."], evidenceToCapture: ["Material and supplier identifiers", "Attribute and process links", "Known contradictions and missing links"], decisionGate: "Every claimed relationship has an evidence locator or is labelled evidence-required." },
      { id: "challenge", title: "Challenge measurement and variability", objective: "Determine whether observed differences can be distinguished from sampling, analytical and normal process variation.", activities: ["Review method capability and sampling alignment.", "Stratify data by bank, lot, supplier, scale and process version.", "Identify confounding changes and missing comparators."], evidenceToCapture: ["Data lineage and method versions", "Lot/batch stratification", "Alternative explanations"], decisionGate: "No causal or control conclusion is allowed when measurement capability or comparability is unresolved." },
      { id: "study", title: "Design bounded evidence generation", objective: "Specify the minimum study or review needed to close the material decision without publishing universal operating ranges.", activities: ["Define study question and contrasts.", "Select response attributes and sampling points.", "Predefine review roles, exclusions and escalation triggers."], evidenceToCapture: ["Protocol question and rationale", "Responses and methods", "Planned decision rule owned by the site"], decisionGate: "The activity is ready only when the site owns methods, criteria and authorization." },
      { id: "decide", title: "Record the decision and lifecycle triggers", objective: "Document what the evidence supports, what stays open and which future changes reopen the assessment.", activities: ["Separate observation, interpretation and disposition.", "Assign open evidence actions.", "Link supplier, bank, process and regulatory change triggers."], evidenceToCapture: ["Decision record", "Open-action register", "Change and monitoring triggers"], decisionGate: "Completion means a review-ready evidence package, not bank approval, process validation or regulatory acceptance." },
    ],
    evidenceActivities: [
      { title: "Bank and lineage evidence challenge", kind: "evidence-review", decisionQuestion: "Is the exact cell substrate and bank-use history sufficiently traceable for the proposed use or comparison?", approach: ["Walk lineage from construct and clone to the working bank in use.", "Check characterization, stability, passage/age and change records against the declared scope.", "Record missing records and conflicting identifiers."], expectedOutputs: ["Versioned lineage map", "Evidence-gap list", "Named review owners"], boundary: "This review does not release a bank or define a universal characterization panel." },
      { title: "Material variability study frame", kind: "study-design", decisionQuestion: "Which material or supplier differences could plausibly move the named upstream or product response?", approach: ["Define the material attributes and contrasts of interest.", "Preserve lot, supplier, storage and process covariates.", "Predefine analytical responses and how inconclusive results will be handled."], expectedOutputs: ["Bounded study question", "Factor–response map", "Site-owned analysis and review plan"], boundary: "No material level, range or supplier equivalence conclusion is supplied." },
      { title: "Upstream signal review", kind: "data-analysis", decisionQuestion: "Do upstream signals remain consistent with the current process understanding and downstream burden?", approach: ["Align time-series and batch data to process phases.", "Review shifts with method and process-version context.", "Separate statistical signals from specification or disposition decisions."], expectedOutputs: ["Signal chronology", "Competing explanations", "Investigation or study triggers"], boundary: "The activity does not create process limits, alarm rules or batch disposition." },
    ],
    knowledgeChecks: [
      { question: "Why is a supplier certificate insufficient to establish material suitability?", expectedReasoning: "A certificate reports selected results for a defined lot; suitability also depends on identity, function, variability, method capability, supply-chain history, process interaction and product-specific evidence." },
      { question: "When may a bank or material change be called comparable?", expectedReasoning: "Only after a product- and change-specific plan, capable methods, predefined evidence expectations and accountable cross-functional review support that conclusion." },
      { question: "What must remain separate when an upstream signal changes?", expectedReasoning: "Observation, measurement capability, normal variability, alternative causes, product impact, investigation status and final disposition must remain distinct." },
    ],
    completionCriteria: ["Scope and lineage are versioned.", "Every material/process link is evidenced or explicitly open.", "Bounded study and review responsibilities are assigned.", "Decision, limitations and lifecycle triggers are recorded."],
  }),
  defineLearningFlow({
    packageId: "biopharma-downstream-analytics-formulation",
    learningObjectives: [
      "Connect purification-step purpose and impurity progression to analytical capability and final product presentation.",
      "Use orthogonal evidence to distinguish clearance, product-quality and formulation questions.",
      "Frame scale-down, hold, stability and fill-finish evidence without inventing platform-wide criteria.",
    ],
    knowledgeUnits: [
      { title: "Step purpose and impurity fate", explanation: "Each downstream operation has an intended separation, conditioning or safety function, with incoming load, step contribution and downstream burden forming the evidence chain.", decisionUse: "Use step-wise mass-balance and method context to locate where evidence is strong, contradictory or absent." },
      { title: "Orthogonal analytical control", explanation: "No single method fully establishes identity, purity, potency, structure or impurity control; complementary methods answer different decision questions and have different limitations.", decisionUse: "Map attributes to intended decisions, methods, reference systems, reportability and lifecycle state." },
      { title: "Formulation, fill-finish and stability", explanation: "Formulation composition, interfaces, holds, mixing, filling, container closure and storage can interact with aggregation, potency, particulates and other quality attributes.", decisionUse: "Connect formulation and presentation choices to evidence rather than treating fill-finish as a passive handoff." },
    ],
    workflowPhases: [
      { id: "scope", title: "Define product, process and decision scope", objective: "Freeze molecule/product, process version, scale, sites, presentation and the downstream-to-formulation decision.", activities: ["Name affected unit operations and attributes.", "Record scale-down and analytical model boundaries.", "Identify viral-safety and quality reviewers where relevant."], evidenceToCapture: ["Process flow and versions", "Attribute list and intended decisions", "Site/scale/presentation boundary"], decisionGate: "The flow cannot proceed with mixed process versions or an undefined product presentation." },
      { id: "map", title: "Map step contribution and analytical coverage", objective: "Trace product and impurity progression through every relevant step and method.", activities: ["Record incoming load and intended step purpose.", "Link each claim to a method and evidence set.", "Identify gaps in orthogonality, reference systems or reportability."], evidenceToCapture: ["Step–attribute–method matrix", "Impurity progression evidence", "Method and reference versions"], decisionGate: "Unmeasured or method-limited claims remain evidence-required." },
      { id: "challenge", title: "Challenge robustness, holds and interfaces", objective: "Test whether evidence represents intended operation, edge conditions and connected handoffs.", activities: ["Review scale-down relevance and reuse/lifetime context.", "Map holds, pool decisions, mixing and fill interfaces.", "Check whether stability observations are linked to formulation/process history."], evidenceToCapture: ["Model qualification basis", "Hold/interface map", "Contradictions and edge cases"], decisionGate: "Do not generalize a platform observation to the product without applicability evidence." },
      { id: "study", title: "Frame confirmation studies", objective: "Define the studies needed to answer clearance, product-quality, formulation or presentation uncertainties.", activities: ["Separate clearance and product-quality endpoints.", "Predefine samples, methods and timepoints conceptually.", "Assign site-owned protocols and criteria."], evidenceToCapture: ["Study question matrix", "Sample/method rationale", "Review and escalation plan"], decisionGate: "Atlas frames the question; qualified teams own execution parameters and acceptance criteria." },
      { id: "decide", title: "Integrate the control and lifecycle decision", objective: "Record how unit operations, methods, formulation and presentation evidence support the bounded decision.", activities: ["Summarize evidence by claim.", "Carry unresolved risks into monitoring or change control.", "Define the next validation, transfer or comparability handoff."], evidenceToCapture: ["Claim-level conclusion table", "Open risks and actions", "Lifecycle handoff"], decisionGate: "Completion is a traceable decision context, not lot release or validation approval." },
    ],
    evidenceActivities: [
      { title: "Step-wise impurity progression review", kind: "data-analysis", decisionQuestion: "Does the evidence show where impurity burden changes and what each step contributes?", approach: ["Align loads, pools and method results by process version.", "Review censored, below-quantitation and missing results explicitly.", "Challenge apparent purge with method capability and mass-balance context."], expectedOutputs: ["Impurity progression map", "Method-limitation register", "Study priorities"], boundary: "No universal purge factor or clearance claim is generated." },
      { title: "Orthogonal method challenge", kind: "challenge-session", decisionQuestion: "Do the combined methods adequately answer the intended identity, purity, potency and structural questions?", approach: ["Assign each method to a decision and attribute.", "Compare strengths, blind spots and reference dependencies.", "Record where agreement or disagreement changes interpretation."], expectedOutputs: ["Attribute–method map", "Orthogonality rationale", "Unresolved measurement questions"], boundary: "This is not analytical validation or specification approval." },
      { title: "Formulation and interface study frame", kind: "study-design", decisionQuestion: "Which formulation, hold, mixing, fill or container interactions require product-specific evidence?", approach: ["Map interfaces and plausible mechanisms.", "Select stability-indicating and performance observations conceptually.", "Predefine product/dosage/presentation scope and review ownership."], expectedOutputs: ["Interface-risk map", "Bounded study questions", "Evidence and reviewer plan"], boundary: "No formulation recipe, fill parameter, shelf life or container suitability conclusion is provided." },
    ],
    knowledgeChecks: [
      { question: "Why can an apparent downstream purge result be misleading?", expectedReasoning: "Incoming load, sampling, recovery, quantitation limits, mass balance, scale-down relevance and process version can all change the interpretation." },
      { question: "What makes analytical evidence orthogonal?", expectedReasoning: "Methods contribute different measurement principles or attribute views; simply running multiple similar methods does not create independent evidence." },
      { question: "Why must formulation and fill-finish remain connected to downstream history?", expectedReasoning: "The product entering formulation carries process- and impurity-related variability that can interact with interfaces, holds, stresses, presentation and stability." },
    ],
    completionCriteria: ["Step purposes and attribute links are explicit.", "Analytical coverage and limitations are traceable.", "Interface/stability studies are bounded and owned.", "The next validation/comparability/transfer questions are carried forward."],
  }),
  defineLearningFlow({
    packageId: "biopharma-validation-comparability-transfer",
    learningObjectives: [
      "Connect process knowledge, qualification, PPQ and continued verification without reducing validation to a batch-count exercise.",
      "Build a change-specific comparability question and evidence hierarchy.",
      "Transfer product, process, method and control knowledge with explicit receiving-site readiness and open risks.",
    ],
    knowledgeUnits: [
      { title: "Lifecycle validation", explanation: "Process design knowledge, facility/equipment readiness, process performance qualification and continued verification are connected evidence states rather than isolated milestones.", decisionUse: "Identify what evidence supports the current state and what must be reopened after material change." },
      { title: "Comparability after change", explanation: "Comparability is a risk- and change-specific evaluation using relevant quality, process, analytical and sometimes clinical/nonclinical evidence; it is not proof that two processes are identical.", decisionUse: "Define the changed attributes, plausible impact and evidence needed before disposition." },
      { title: "Technology-transfer readiness", explanation: "A transfer succeeds when knowledge, methods, materials, facilities, controls, deviations and responsibilities can be executed and governed at the receiving site.", decisionUse: "Use readiness evidence and unresolved gaps to sequence transfer activities and escalation." },
    ],
    workflowPhases: [
      { id: "scope", title: "Freeze lifecycle state and change scope", objective: "Record product, process, sites, scales, validation state, change description and intended decision.", activities: ["Identify affected process and analytical elements.", "Link current validation and regulatory state.", "Name sending/receiving and accountable reviewers."], evidenceToCapture: ["Change and lifecycle baseline", "Affected-system map", "Decision and ownership record"], decisionGate: "No comparability or transfer plan proceeds without a stable baseline and change definition." },
      { id: "risk", title: "Map impact and evidence hypotheses", objective: "Connect change mechanisms to attributes, process performance, methods, controls and patient/product risk.", activities: ["Build a change–mechanism–attribute map.", "Separate prior knowledge from product evidence.", "Rank open questions without converting rank into acceptance."], evidenceToCapture: ["Impact map", "Prior-knowledge applicability", "Evidence-required questions"], decisionGate: "Every excluded question requires an explicit rationale and reviewer." },
      { id: "design", title: "Design validation, comparability and transfer evidence", objective: "Define linked evidence packages and their decision roles.", activities: ["Map qualification/PPQ/CPV evidence.", "Define analytical and process comparability tiers.", "Build receiving-site readiness and knowledge-transfer plan."], evidenceToCapture: ["Evidence hierarchy", "Study/protocol ownership", "Transfer readiness matrix"], decisionGate: "Criteria and execution details remain controlled by qualified product/site teams." },
      { id: "execute-review", title: "Review execution and emerging signals", objective: "Preserve protocol deviations, method limitations, unexpected signals and site differences during execution.", activities: ["Review evidence against the intended question.", "Reconcile process and analytical signals.", "Escalate deviations and unresolved comparability risks."], evidenceToCapture: ["Execution evidence index", "Deviation and signal log", "Cross-functional review record"], decisionGate: "An unexplained material signal prevents a closed comparability or validation conclusion." },
      { id: "lifecycle", title: "Authorize the bounded next state", objective: "Document disposition, continued monitoring, residual risks and receiving-site responsibilities.", activities: ["Separate technical conclusion from authorization.", "Set CPV/change triggers and knowledge owners.", "Record what evidence transfers to the next lifecycle stage."], evidenceToCapture: ["Disposition and authorization record", "CPV/monitoring commitments", "Residual-risk and knowledge-transfer register"], decisionGate: "The package supports review; it does not approve PPQ, comparability, site transfer or regulatory filing." },
    ],
    evidenceActivities: [
      { title: "Validation evidence continuity review", kind: "evidence-review", decisionQuestion: "Does the current validation state trace from process knowledge through qualification and continued verification?", approach: ["Map claims to design, qualification, PPQ and CPV evidence.", "Identify changes that break continuity.", "Separate statistical signals from approved control/disposition rules."], expectedOutputs: ["Lifecycle evidence map", "Broken-link register", "Revalidation or review questions"], boundary: "No universal batch count, sampling plan or CPV rule is supplied." },
      { title: "Comparability study architecture", kind: "study-design", decisionQuestion: "What evidence hierarchy is proportionate to the specific manufacturing change?", approach: ["Define change mechanisms and potentially affected attributes.", "Select analytical/process evidence tiers and relevant comparators.", "Predefine how discordant or inconclusive evidence will be escalated."], expectedOutputs: ["Change-specific comparability plan", "Attribute/evidence hierarchy", "Escalation logic"], boundary: "The activity does not issue a comparability conclusion or regulatory precedent." },
      { title: "Receiving-site transfer simulation", kind: "transfer-simulation", decisionQuestion: "Can the receiving site explain and execute the critical knowledge and controls with open gaps visible?", approach: ["Walk one representative material/process/method chain.", "Challenge roles, facilities, methods, data and deviation routes.", "Record assumptions that require qualification or local confirmation."], expectedOutputs: ["Readiness observations", "Knowledge-gap register", "Sequenced transfer actions"], boundary: "Simulation completion is not site readiness, qualification or transfer authorization." },
    ],
    knowledgeChecks: [
      { question: "Why is process validation not demonstrated by a fixed number of successful batches alone?", expectedReasoning: "The conclusion depends on process knowledge, facility/equipment and method readiness, protocol scope, execution evidence, variability, deviations and continued verification." },
      { question: "Does comparability mean the pre- and post-change processes are identical?", expectedReasoning: "No. It asks whether relevant evidence supports that the change does not adversely affect quality within the defined product and change scope." },
      { question: "What is the difference between knowledge transfer and transfer authorization?", expectedReasoning: "Knowledge transfer makes rationale and execution information usable; authorization is an accountable controlled decision based on complete site/product evidence." },
    ],
    completionCriteria: ["Lifecycle baseline and change scope are frozen.", "Validation/comparability/transfer evidence is linked by claim.", "Unexplained signals and residual risks remain open.", "Authorization, monitoring and knowledge ownership are explicit."],
  }),
];
