import { defineLearningFlow } from "../decision-package-learning-types";

export const CROSS_CUTTING_DECISION_PACKAGE_LEARNING_FLOWS = [
  defineLearningFlow({
    packageId: "cross-cutting-evidence-governance",
    learningObjectives: ["Move an analytical or process signal through evidence review, investigation, CAPA, change and effectiveness without losing lineage.", "Use statistics and designed evidence to improve decisions without converting models into automatic disposition rules.", "Transfer reusable knowledge across products and sites while preserving applicability, limitations and authorization."],
    knowledgeUnits: [
      { title: "Signal, result and decision are different objects", explanation: "A data signal may trigger review; a valid reportable result has method and data context; a quality decision also requires product/process impact, procedure and accountable authority.", decisionUse: "Keep detection, interpretation, investigation and disposition separate in the evidence trail." },
      { title: "Investigation and CAPA logic", explanation: "A defensible investigation preserves the event, data, hypotheses, tests, product impact and rationale; CAPA addresses supported causes or system weaknesses and requires effectiveness evidence.", decisionUse: "Prevent unsupported root-cause labels and activity-completion masquerading as effectiveness." },
      { title: "Change and knowledge lifecycle", explanation: "Confirmed learning becomes reusable only after applicability, impact, ownership, versioning and approval are controlled; conflicting or inconclusive evidence remains visible.", decisionUse: "Transfer knowledge without silently changing specifications, procedures, rules or Domain Packs." },
    ],
    workflowPhases: [
      { id: "detect", title: "Capture the signal and preserve context", objective: "Record what was observed, when, by which method/system, for which product/process/version and under which controls.", activities: ["Freeze original data and metadata references.", "Separate initial observation from interpretation.", "Identify immediate procedural containment owned by the site."], evidenceToCapture: ["Signal/event record", "Data/method/process versions", "Containment and authority record"], decisionGate: "Do not classify cause, product impact or CAPA before the evidence basis is preserved." },
      { id: "assess", title: "Assess validity, scope and potential impact", objective: "Determine what evidence is credible, what population may be affected and which decisions are open.", activities: ["Review method, sample and data integrity context.", "Map batches/products/processes/sites and time window.", "Identify contradictory evidence and urgent escalation questions."], evidenceToCapture: ["Validity assessment", "Scope/impact map", "Contradiction and gap register"], decisionGate: "Unknown validity or scope keeps material conclusions evidence-required." },
      { id: "investigate", title: "Test competing hypotheses", objective: "Use a documented hypothesis set and discriminating evidence rather than selecting a convenient cause.", activities: ["Develop technical, human, procedural and system hypotheses.", "Prioritize tests by ability to discriminate.", "Record negative, inconclusive and contradictory evidence."], evidenceToCapture: ["Hypothesis/evidence matrix", "Test and analysis records", "Cause confidence and limitations"], decisionGate: "A root cause is not closed when plausible competing explanations remain materially unresolved." },
      { id: "act", title: "Design correction, CAPA or change", objective: "Select actions that match supported causes, control immediate risk and address recurrence/system weakness.", activities: ["Separate correction, corrective action, preventive/system action and change.", "Assess unintended consequences and affected controls.", "Define implementation evidence and accountable owners."], evidenceToCapture: ["Action rationale", "Impact/change assessment", "Implementation and ownership plan"], decisionGate: "Training, procedure revision or task completion alone is not proof of effectiveness." },
      { id: "verify-transfer", title: "Verify effectiveness and govern learning", objective: "Evaluate whether the intended outcome occurred and decide what knowledge may be reused.", activities: ["Define outcome, observation window and comparison basis.", "Review recurrence and leading/lagging signals.", "Version reusable knowledge with applicability and approval boundaries."], evidenceToCapture: ["Effectiveness evidence", "Residual-risk decision", "Knowledge/version/approval record"], decisionGate: "No result updates an Atlas rule, benchmark or Domain Pack automatically." },
    ],
    evidenceActivities: [
      { title: "Signal-to-decision lineage reconstruction", kind: "evidence-review", decisionQuestion: "Can the final decision be traced to original data, methods, hypotheses, reviews and authority?", approach: ["Walk backward from disposition to evidence.", "Verify versions, timestamps and decision owners.", "Record broken, circular or unsupported links."], expectedOutputs: ["Decision lineage map", "Broken-link register", "Remediation actions"], boundary: "Reconstruction does not validate the underlying method, system or decision." },
      { title: "Competing-hypothesis analysis", kind: "data-analysis", decisionQuestion: "Which evidence discriminates among plausible explanations, and what remains unresolved?", approach: ["List hypotheses before interpreting new results.", "Map expected observations and actual evidence.", "Retain negative and conflicting results in the conclusion."], expectedOutputs: ["Hypothesis evidence matrix", "Confidence/limitation statement", "Next discriminating test"], boundary: "Atlas does not assign root cause or product disposition." },
      { title: "CAPA effectiveness study frame", kind: "study-design", decisionQuestion: "What observable outcome would demonstrate that the action addressed the supported problem without creating new risk?", approach: ["Define intended mechanism and outcome.", "Choose observation window, population and comparison conceptually.", "Predefine recurrence, confounding and escalation handling."], expectedOutputs: ["Effectiveness question", "Measure/context plan", "Close, extend or reassess decision inputs"], boundary: "No universal threshold, duration or CAPA closure rule is provided." },
    ],
    knowledgeChecks: [
      { question: "Why must a statistical signal remain separate from a specification failure?", expectedReasoning: "They answer different questions and trigger different controlled processes; statistical unusualness does not itself define conformance or disposition." },
      { question: "What makes a root-cause conclusion defensible?", expectedReasoning: "Preserved evidence, plausible hypotheses, discriminating tests, treatment of contradictions, supported causal reasoning, scope/impact review and accountable approval." },
      { question: "What distinguishes CAPA completion from effectiveness?", expectedReasoning: "Completion shows actions were performed; effectiveness shows the intended risk or system outcome changed over an appropriate, defined evidence window." },
    ],
    completionCriteria: ["Signal-to-decision lineage is reconstructable.", "Competing hypotheses and contradictions are retained.", "Actions map to supported causes and impacts.", "Effectiveness and knowledge reuse have explicit evidence, scope and authority."],
  }),
];
