import { defineLearningFlow } from "../decision-package-learning-types";

export const DRUG_PRODUCT_DECISION_PACKAGE_LEARNING_FLOWS = [
  defineLearningFlow({
    packageId: "drug-product-formulation-material-attributes",
    learningObjectives: ["Connect product-performance intent to API, excipient and formulation attributes.", "Separate general formulation reasoning from the bounded synthetic OSD example.", "Frame material-function, compatibility and manufacturability evidence without creating a formula or design space."],
    knowledgeUnits: [
      { title: "Quality target and formulation intent", explanation: "A formulation begins with the intended product, dosage form, route, performance and patient-use context; component choices are hypotheses about how those needs may be met.", decisionUse: "Use the target to define evidence questions rather than reverse-engineering universal component levels." },
      { title: "API and excipient attributes", explanation: "Physical, chemical and functional attributes can influence processing, stability, release and performance, but relevance depends on material source, method, formulation and dosage form.", decisionUse: "Map attributes to plausible effects, measurements and evidence state without declaring causality prematurely." },
      { title: "Compatibility and manufacturability", explanation: "Component interactions, environmental exposure, process stresses, packaging and storage can change product behavior across the lifecycle.", decisionUse: "Connect formulation questions to process, analytical, stability and packaging evidence before a decision." },
    ],
    workflowPhases: [
      { id: "scope", title: "Define product and dosage-form boundary", objective: "Freeze intended product, route, dosage form, presentation, lifecycle stage and decision.", activities: ["Record target performance questions.", "Identify OSD example elements as synthetic only.", "Name formulation, material, process, analytical, quality and regulatory reviewers."], evidenceToCapture: ["Product target and scope", "Dosage-form applicability", "Decision and reviewer map"], decisionGate: "No OSD observation may be generalized to another dosage form or product." },
      { id: "map", title: "Map component function and attributes", objective: "Connect each API/excipient/material input to intended function, relevant attributes and measurement evidence.", activities: ["Record exact material source, grade and role.", "Map plausible attribute–performance relationships.", "Separate prior knowledge, observation and demonstrated impact."], evidenceToCapture: ["Component-function matrix", "Attribute/method links", "Hypothesis and evidence labels"], decisionGate: "A material-function label is not evidence of product-specific performance." },
      { id: "challenge", title: "Challenge compatibility and variability", objective: "Identify material, supplier, environmental, process and packaging interactions that could change the formulation decision.", activities: ["Review material and formulation history.", "Map moisture, temperature, light, oxygen and mechanical exposure questions.", "Identify confounding process or method changes."], evidenceToCapture: ["Interaction-risk map", "Variability stratification", "Contradictions and unknowns"], decisionGate: "Unresolved measurement or comparator limitations prevent causal claims." },
      { id: "study", title: "Design bounded formulation evidence", objective: "Frame studies that can discriminate among formulation and material hypotheses.", activities: ["Define factors and responses conceptually.", "Include process, analytical, stability and packaging observations as relevant.", "Predefine site-owned criteria, escalation and reviewer roles."], evidenceToCapture: ["Study question and rationale", "Factor–response plan", "Decision and escalation ownership"], decisionGate: "Atlas provides no formula, level, operating range, design space or bioequivalence conclusion." },
      { id: "decide", title: "Record formulation evidence decision", objective: "State what may proceed for further development, what stays open and which changes reopen the assessment.", activities: ["Separate selection-for-study from product approval.", "Assign missing evidence and lifecycle triggers.", "Handoff material questions to unit-operation development."], evidenceToCapture: ["Bounded decision record", "Open-evidence register", "Process-development handoff"], decisionGate: "Completion is a review-ready planning package, not a formulation, validation case or regulatory precedent." },
    ],
    evidenceActivities: [
      { title: "Material-function evidence map", kind: "evidence-review", decisionQuestion: "What evidence supports each component's intended function and product-specific relevance?", approach: ["Trace exact material, source, grade, method and formulation context.", "Separate general knowledge from product observations.", "Record contradictions and untested interactions."], expectedOutputs: ["Function–attribute–evidence matrix", "Applicability limits", "Study priorities"], boundary: "No component selection or level is recommended." },
      { title: "Compatibility study architecture", kind: "study-design", decisionQuestion: "Which component, environmental and presentation interactions require evidence?", approach: ["Define plausible interaction mechanisms.", "Select stability-indicating and performance observations conceptually.", "Preserve controls, sample history and dosage-form scope."], expectedOutputs: ["Interaction study questions", "Observation/method plan", "Review triggers"], boundary: "No storage condition, shelf life or compatibility conclusion is issued." },
      { title: "Synthetic OSD scenario challenge", kind: "challenge-session", decisionQuestion: "Which parts of the OSD example are transferable reasoning and which are example-specific?", approach: ["Mark general decision questions separately from synthetic facts.", "Identify dosage-form and product assumptions.", "Rewrite non-transferable statements as evidence questions."], expectedOutputs: ["Reusable question set", "Non-applicable example elements", "Reviewer notes"], boundary: "The scenario is not a recipe, development history, validation case or precedent." },
    ],
    knowledgeChecks: [
      { question: "Why is an excipient's compendial name insufficient to establish functional equivalence?", expectedReasoning: "Source, grade, physical/chemical attributes, processing history, method and formulation context can change functionality." },
      { question: "What distinguishes a formulation hypothesis from a demonstrated relationship?", expectedReasoning: "A demonstrated relationship needs suitable comparators, capable measurements, controlled context, relevant data and review of alternative explanations." },
      { question: "What may be reused from the synthetic OSD example?", expectedReasoning: "The decision structure and evidence questions may be reused; formula, levels, ranges, results, applicability and conclusions may not." },
    ],
    completionCriteria: ["Product/dosage-form scope is explicit.", "Component claims are evidence-labelled.", "Bounded study questions cover process and stability interactions.", "No formula, design space or approval claim is produced."],
  }),
  defineLearningFlow({
    packageId: "drug-product-unit-operations-scale-up",
    learningObjectives: ["Connect unit-operation purpose and material transformation to product attributes.", "Translate scale using mechanism, equipment and measurement evidence.", "Frame process studies and controls without universal parameters or validation conclusions."],
    knowledgeUnits: [
      { title: "Unit-operation purpose", explanation: "Dispensing, blending, granulation, drying, milling, lubrication, compression/coating or other dosage-form operations each create or preserve a defined material state.", decisionUse: "Map the operation's intended transformation and what evidence shows it occurred." },
      { title: "Material–process interaction", explanation: "Flow, cohesion, moisture, particle, density, lubrication, compaction and other relevant attributes can interact with equipment and sequence in product-specific ways.", decisionUse: "Use mechanistic hypotheses to select measurements and studies, not to assign generic parameter ranges." },
      { title: "Scale and control strategy", explanation: "Scale changes geometry, residence, mixing, heat/mass transfer, feed and control response; process controls must be justified by their relationship to the intended output.", decisionUse: "Link each proposed parameter, attribute or endpoint to evidence, applicability and monitoring." },
    ],
    workflowPhases: [
      { id: "scope", title: "Freeze process and equipment scope", objective: "Define dosage form, formulation version, batch scale, equipment train, site and decision.", activities: ["Map actual unit-operation sequence.", "Record equipment modes and material states.", "Name process, engineering, analytical, quality and validation reviewers."], evidenceToCapture: ["Process/equipment map", "Material/formulation version", "Scale and decision scope"], decisionGate: "Do not compare batches or scales with incompatible process/formulation versions." },
      { id: "map", title: "Map transformations and attributes", objective: "Connect inputs, operation purpose, process observations and resulting material/product attributes.", activities: ["Define intended transformation per step.", "Map relevant material attributes and responses.", "Identify sampling and method limitations."], evidenceToCapture: ["Input–operation–output map", "Attribute/measurement links", "Unresolved mechanisms"], decisionGate: "Nominal completion of an operation is not proof of the intended material state." },
      { id: "scale", title: "Challenge scale and equipment differences", objective: "Identify scale-dependent mechanisms and equipment-specific risks.", activities: ["Compare geometry, load, feed, energy and control modes.", "Map residence, transfer and hold differences.", "Identify observables that test the hypotheses."], evidenceToCapture: ["Scale translation matrix", "Equipment differences", "Monitoring questions"], decisionGate: "A dimensionless or normalized metric is supporting evidence, not automatic equivalence." },
      { id: "study", title: "Design process and robustness evidence", objective: "Frame studies that connect factors to meaningful material/product responses.", activities: ["Select factors using risk and prior knowledge.", "Preserve intermediate and finished-product sample lineage.", "Predefine analysis, deviations and follow-up ownership."], evidenceToCapture: ["Study architecture", "Factor–response rationale", "Site-owned protocol/criteria"], decisionGate: "No process range, setpoint, batch size or design space is issued." },
      { id: "decide", title: "Record process-control decision", objective: "Document supported understanding, proposed controls for review and lifecycle evidence needs.", activities: ["Separate observed relationship from approved control.", "Assign scale-up, validation and monitoring gaps.", "Handoff analytical and stability implications."], evidenceToCapture: ["Process evidence summary", "Control rationale draft", "Validation/analytical handoff"], decisionGate: "Completion is not PPQ, process validation or manufacturing authorization." },
    ],
    evidenceActivities: [
      { title: "Unit-operation transformation review", kind: "evidence-review", decisionQuestion: "What evidence shows each operation delivered its intended material transformation?", approach: ["Align inputs, settings, observations, intermediates and outputs.", "Check sample/method representativeness.", "Record unexplained variability and failed transformations."], expectedOutputs: ["Operation evidence chain", "Measurement gaps", "Study priorities"], boundary: "No parameter range or batch disposition is produced." },
      { title: "Scale translation study frame", kind: "study-design", decisionQuestion: "Which equipment and scale mechanisms could move the relevant responses?", approach: ["Compare physical configuration and operating modes.", "Select measurable mechanism and product responses.", "Define applicability to exact scales/equipment."], expectedOutputs: ["Scale-risk hypotheses", "Comparison study plan", "Escalation criteria owned by the site"], boundary: "No scale-up recipe or equipment equivalence is claimed." },
      { title: "Process interruption challenge", kind: "challenge-session", decisionQuestion: "How would holds, stoppages, rework or material transfer change the evidence chain?", approach: ["Walk credible interruption scenarios.", "Map material-state and traceability impacts.", "Assign evidence, procedural and change-control needs."], expectedOutputs: ["Interruption-risk map", "Open evidence", "Governance actions"], boundary: "No rework authorization or hold time is established." },
    ],
    knowledgeChecks: [
      { question: "Why should every unit operation have an explicit intended transformation?", expectedReasoning: "It connects inputs and process observations to the material state required by subsequent operations and product performance." },
      { question: "Why can equipment of similar nominal capacity behave differently?", expectedReasoning: "Geometry, energy delivery, feed, controls, dead zones, transfer and measurement can differ materially." },
      { question: "When does a process parameter become part of a justified control strategy?", expectedReasoning: "When its relationship to process/material/product risk is supported by relevant evidence, measurement and accountable lifecycle review." },
    ],
    completionCriteria: ["Every operation has a transformation/evidence chain.", "Scale and equipment applicability is explicit.", "Studies are mechanism-based and site-owned.", "Validation and analytical gaps are carried forward."],
  }),
  defineLearningFlow({
    packageId: "drug-product-analytical-release-stability-packaging",
    learningObjectives: ["Connect analytical performance and release decisions to formulation/process knowledge.", "Integrate stability, dissolution/performance and packaging evidence over the product lifecycle.", "Separate measurement signals, specification decisions and batch disposition."],
    knowledgeUnits: [
      { title: "Analytical and release evidence", explanation: "Release decisions combine approved specifications, capable procedures, representative samples, data integrity, manufacturing history and quality review.", decisionUse: "Trace what each result can support and what remains outside the method's capability or scope." },
      { title: "Stability-indicating performance", explanation: "A stability program must detect meaningful change using suitable methods, controlled storage/pulls and product/package-specific interpretation.", decisionUse: "Connect trends to degradation, variability, method and package context without setting shelf life from an isolated result." },
      { title: "Packaging and product performance", explanation: "Container closure, moisture/oxygen/light protection, compatibility, integrity and patient-use interactions can affect quality and performance throughout storage and distribution.", decisionUse: "Treat packaging as part of the product evidence chain, not a separate procurement item." },
    ],
    workflowPhases: [
      { id: "scope", title: "Freeze product, method and package scope", objective: "Define formulation/process batch, methods, specifications, package configuration, markets, storage and decision.", activities: ["Record exact method/specification versions.", "Map package components and configurations.", "Name QC, analytical, stability, packaging, quality and regulatory reviewers."], evidenceToCapture: ["Product/batch context", "Method/specification versions", "Package/stability scope"], decisionGate: "No release or stability interpretation proceeds with mixed versions or unidentified package configuration." },
      { id: "map", title: "Map attribute–method–decision coverage", objective: "Connect quality/performance attributes to methods, reportable results, specifications and intended decisions.", activities: ["Map release and stability uses separately.", "Review reference, sample and system controls.", "Identify method blind spots and overlapping evidence."], evidenceToCapture: ["Attribute–method–decision matrix", "Method limitations", "Specification basis links"], decisionGate: "Passing a test does not support an attribute the method cannot adequately measure." },
      { id: "stability-package", title: "Connect stability and packaging mechanisms", objective: "Trace degradation, transport and package-protection questions to evidence.", activities: ["Align batches, conditions, pulls, methods and package lots.", "Map moisture, oxygen, light, integrity and compatibility hypotheses.", "Identify excursions and method/package changes."], evidenceToCapture: ["Stability chronology", "Package–risk map", "Excursion and change records"], decisionGate: "Trends cannot be interpreted without method, batch, condition and package context." },
      { id: "challenge", title: "Challenge release and lifecycle signals", objective: "Separate valid result, statistical/visual trend, specification status, investigation and disposition.", activities: ["Review atypical, OOT and OOS signals.", "Trace manufacturing and sampling context.", "Define packaging/stability or method follow-up."], evidenceToCapture: ["Signal assessment", "Investigation links", "Follow-up evidence plan"], decisionGate: "No automated release, rejection, shelf-life or packaging conclusion is permitted." },
      { id: "decide", title: "Record analytical-product lifecycle decision", objective: "Document bounded evidence conclusions, open signals and validation/change handoff.", activities: ["State scope and method limitations.", "Assign stability, packaging, investigation and change actions.", "Carry relevant evidence to continued verification."], evidenceToCapture: ["Decision-context summary", "Open action/owner register", "Lifecycle handoff"], decisionGate: "Completion supports qualified review; it is not batch release or regulatory approval." },
    ],
    evidenceActivities: [
      { title: "Release evidence trace", kind: "evidence-review", decisionQuestion: "Can every material release statement be traced to approved context, representative sample, procedure and quality review?", approach: ["Trace result to sample, batch, method, calculation and specification version.", "Review deviations and manufacturing context.", "Record what the result cannot establish."], expectedOutputs: ["Release evidence trace", "Data/method gaps", "Review questions"], boundary: "The activity does not release or reject a batch." },
      { title: "Stability trend review", kind: "data-analysis", decisionQuestion: "Which changes are credible signals after accounting for batch, method, package and condition context?", approach: ["Align results chronologically and by configuration.", "Review method/version and censored-data changes.", "Separate trend from approved shelf-life/specification decision."], expectedOutputs: ["Contextual trend package", "Competing explanations", "Investigation/study triggers"], boundary: "No shelf life, extrapolation or acceptance criterion is generated." },
      { title: "Packaging challenge study frame", kind: "study-design", decisionQuestion: "Which package functions or interactions need evidence for the product and intended distribution/use?", approach: ["Map protection, compatibility, integrity and use functions.", "Define product-specific challenges and observations conceptually.", "Preserve package lot/configuration and product history."], expectedOutputs: ["Package-function evidence map", "Study questions", "Review and escalation ownership"], boundary: "No package qualification, integrity method or suitability conclusion is supplied." },
    ],
    knowledgeChecks: [
      { question: "Why is an in-specification result not the whole release decision?", expectedReasoning: "Method validity, sample representativeness, manufacturing/deviation history, data integrity and Quality Unit disposition also matter." },
      { question: "What makes a method stability-indicating?", expectedReasoning: "It can meaningfully detect and distinguish relevant product change/degradation for the intended matrix and use, supported by appropriate evidence." },
      { question: "Why must packaging configuration stay linked to stability data?", expectedReasoning: "Protection, compatibility, integrity and exposure can differ by component, supplier, configuration and lifecycle state." },
    ],
    completionCriteria: ["Methods and decisions are mapped by intended use.", "Stability and packaging evidence retains exact context.", "Signals and dispositions remain separate.", "Open investigation/change actions are owned."],
  }),
  defineLearningFlow({
    packageId: "drug-product-validation-transfer-lifecycle",
    learningObjectives: ["Connect process validation, method transfer and site transfer to product/process knowledge.", "Assess change impact across formulation, process, analytical, stability, packaging and filing evidence.", "Define continued lifecycle monitoring and knowledge governance without approving validation or change."],
    knowledgeUnits: [
      { title: "Drug-product validation lifecycle", explanation: "Process design, equipment/facility readiness, PPQ and continued verification form a connected evidence lifecycle tailored to the product, dosage form and process.", decisionUse: "Identify evidence continuity and which product/process changes reopen validation questions." },
      { title: "Integrated transfer", explanation: "Product, material, process, analytical, packaging, cleaning, data and quality-system knowledge must be usable at the receiving site with local differences visible.", decisionUse: "Sequence readiness, protocol and gap closure before transfer authorization." },
      { title: "Change and continued lifecycle", explanation: "A change can affect multiple linked evidence systems; monitoring, investigations, stability and knowledge management determine whether the approved state remains supported.", decisionUse: "Trace affected claims, evidence, commitments and owners before disposition." },
    ],
    workflowPhases: [
      { id: "scope", title: "Freeze baseline, sites and change scope", objective: "Define product/formulation/process/package/method versions, validation state, sites and decision.", activities: ["Record sending and receiving baselines.", "Map the change or transfer boundary.", "Name technical, quality, validation and regulatory owners."], evidenceToCapture: ["Controlled baseline", "Affected-system map", "Decision/reviewer record"], decisionGate: "No transfer or change assessment proceeds without exact source and target states." },
      { id: "impact", title: "Map cross-system impact", objective: "Connect the proposed change/transfer to materials, operations, methods, cleaning, stability, packaging, data and filings.", activities: ["Build claim/evidence impact map.", "Separate prior knowledge from local evidence.", "Identify regulatory and validation commitments for review."], evidenceToCapture: ["Impact matrix", "Applicability rationale", "Evidence-required register"], decisionGate: "Every excluded system or attribute requires documented rationale and accountable review." },
      { id: "readiness", title: "Assess transfer and validation readiness", objective: "Determine whether facilities, equipment, methods, people, materials and governance can support planned execution.", activities: ["Review gap and training evidence.", "Map method/process transfer protocols.", "Confirm deviation, data and escalation pathways."], evidenceToCapture: ["Readiness matrix", "Protocol/evidence links", "Open gap owners"], decisionGate: "Training completion or document receipt alone is not demonstrated readiness." },
      { id: "execute", title: "Review execution, deviations and comparability", objective: "Preserve emerging evidence and differences during qualification, transfer or change implementation.", activities: ["Review planned versus actual execution.", "Reconcile analytical, process and stability signals.", "Escalate unexplained differences and protocol deviations."], evidenceToCapture: ["Execution evidence index", "Difference/deviation log", "Cross-functional review"], decisionGate: "Unresolved material differences prevent a closed validation or transfer conclusion." },
      { id: "continue", title: "Record disposition and continued verification", objective: "Document authorization boundaries, monitoring, commitments and knowledge ownership after the decision.", activities: ["Separate technical recommendation from controlled approval.", "Define continued verification and stability triggers.", "Transfer residual risks into CAPA/change/knowledge systems."], evidenceToCapture: ["Disposition record", "Monitoring/commitment plan", "Knowledge and residual-risk register"], decisionGate: "The package does not approve PPQ, transfer, change, filing or commercial manufacture." },
    ],
    evidenceActivities: [
      { title: "Receiving-site readiness simulation", kind: "transfer-simulation", decisionQuestion: "Can the receiving site execute and explain the critical product/process/method chain with current evidence?", approach: ["Walk a representative batch and method chain.", "Challenge material, equipment, data and deviation handoffs.", "Record local differences and missing qualification evidence."], expectedOutputs: ["Readiness observations", "Gap/action register", "Protocol questions"], boundary: "Simulation is not site qualification or transfer authorization." },
      { title: "Change-impact evidence challenge", kind: "challenge-session", decisionQuestion: "Which approved or evidence-backed claims could the proposed change affect?", approach: ["Trace change mechanisms across linked systems.", "Review prior knowledge applicability and contradictory evidence.", "Assign product/site-specific confirmation needs."], expectedOutputs: ["Claim-level impact map", "Evidence needs", "Reviewer/authority matrix"], boundary: "No change approval or regulatory classification is issued." },
      { title: "Continued verification signal review", kind: "data-analysis", decisionQuestion: "Do post-transfer or post-change signals remain consistent with the supported state?", approach: ["Align process, analytical, deviation, stability and complaint signals.", "Preserve versions and implementation dates.", "Separate statistical signal, investigation and approved response."], expectedOutputs: ["Post-change chronology", "Signal hypotheses", "Escalation and study actions"], boundary: "No universal monitoring rule or validated-state conclusion is generated." },
    ],
    knowledgeChecks: [
      { question: "Why is document transfer insufficient for technology transfer?", expectedReasoning: "Tacit rationale, local equipment/material/method differences, execution capability, data pathways, deviations and accountable decisions must also be demonstrated." },
      { question: "What is the minimum boundary for a useful change-impact assessment?", expectedReasoning: "Exact baseline and proposed state, affected product/sites/markets, plausible mechanisms, linked evidence/commitments, unknowns and accountable reviewers." },
      { question: "Does a stable post-change trend automatically prove the change was acceptable?", expectedReasoning: "No. Method capability, duration, representativeness, expected risks, deviations and predefined evidence expectations must be considered." },
    ],
    completionCriteria: ["Baseline/source/target states are versioned.", "Cross-system impacts and exclusions are justified.", "Readiness and execution gaps are visible.", "Disposition, continued monitoring and knowledge ownership are explicit."],
  }),
];
