import { defineLearningFlow } from "../decision-package-learning-types";

export const PHARMA_API_DECISION_PACKAGE_LEARNING_FLOWS = [
  defineLearningFlow({
    packageId: "pharma-api-route-inputs-suppliers",
    learningObjectives: ["Define the exact route, starting-material boundary and supplier input scope.", "Connect input attributes and supplier controls to process and impurity questions.", "Frame qualification, change-notification and incoming-verification evidence without approving a supplier."],
    knowledgeUnits: [
      { title: "Route and starting-material boundary", explanation: "The proposed starting point must be understood in the context of the synthetic route, fate of impurities, process knowledge and the controls applied before and after introduction.", decisionUse: "Use route position and impurity fate to identify evidence questions; do not infer regulatory acceptability from naming alone." },
      { title: "Input criticality and functionality", explanation: "Starting materials, reagents, solvents, catalysts, processing aids and utilities affect different process steps and quality risks.", decisionUse: "Map intended use, relevant attributes, variability and downstream detectability or control for each input." },
      { title: "Supplier lifecycle control", explanation: "Qualification defines an approved material–site–grade–route scope and continues through incoming verification, performance monitoring, change notification and requalification.", decisionUse: "Separate supplier evidence from the regulated manufacturer's material disposition and change decisions." },
    ],
    workflowPhases: [
      { id: "scope", title: "Freeze route and input scope", objective: "Identify route version, proposed starting point, input grades/sites and the decision to support.", activities: ["Map route steps before and after the proposed boundary.", "Record material, manufacturer, site, grade and supply route.", "Name process, analytical, quality, supplier-quality and regulatory reviewers."], evidenceToCapture: ["Route and material identifiers", "Supplier/manufacturing-site scope", "Decision and market context"], decisionGate: "Stop if route version, actual manufacturer or material grade is unknown." },
      { id: "map", title: "Map input–process–impurity relationships", objective: "Trace how each input may affect reaction performance, impurity formation, carryover and downstream control.", activities: ["Record input function and introduction step.", "Map known and plausible impurities without asserting fate.", "Identify analytical visibility and downstream control points."], evidenceToCapture: ["Input-function matrix", "Impurity hypothesis map", "Method and control links"], decisionGate: "Every asserted fate or purge claim needs route-specific evidence." },
      { id: "qualify", title: "Build the supplier and material evidence set", objective: "Scale qualification evidence to the defined risk and scope.", activities: ["Review manufacturer and supply-chain evidence.", "Define quality-agreement and notification questions.", "Map incoming identity/verification and periodic confirmation responsibilities."], evidenceToCapture: ["Qualification evidence index", "Quality-agreement responsibility map", "Incoming-verification basis"], decisionGate: "A certificate or audit alone cannot close material suitability and route-control questions." },
      { id: "challenge", title: "Challenge variability and change scenarios", objective: "Identify supplier, site, grade, process, specification and analytical changes that could alter the route evidence chain.", activities: ["Compare historical lots and deviations where available.", "Run change-notification scenarios.", "Define evidence required before reduced testing or alternate-source use."], evidenceToCapture: ["Variability summary", "Change scenario register", "Requalification triggers"], decisionGate: "Unknown material differences remain evidence-required and cannot be treated as equivalent." },
      { id: "decide", title: "Record bounded input-control disposition", objective: "Document the exact approved-for-review scope, controls, open evidence and monitoring triggers.", activities: ["Separate technical assessment from supplier/material approval.", "Assign evidence and change actions.", "Carry route and impurity questions into process development."], evidenceToCapture: ["Scope-specific disposition draft", "Open-action owners", "Downstream handoff"], decisionGate: "Completion does not approve a starting material, supplier, reduced-testing program or regulatory position." },
    ],
    evidenceActivities: [
      { title: "Route-boundary challenge", kind: "challenge-session", decisionQuestion: "What evidence supports the proposed starting-material position within this exact route?", approach: ["Trace structural complexity and route steps conceptually.", "Review impurity fate/control and analytical visibility.", "Record assumptions requiring regulatory CMC review."], expectedOutputs: ["Boundary rationale map", "Evidence gaps", "Regulatory review questions"], boundary: "No starting-material designation or filing acceptability is issued." },
      { title: "Input variability review", kind: "data-analysis", decisionQuestion: "Which input attributes or supplier differences align with process or impurity signals?", approach: ["Stratify by manufacturer, site, grade and lot.", "Preserve process-version and method context.", "Distinguish correlation from demonstrated mechanism."], expectedOutputs: ["Stratified observation table", "Competing explanations", "Targeted study questions"], boundary: "No universal material specification or equivalence claim is generated." },
      { title: "Supplier change simulation", kind: "transfer-simulation", decisionQuestion: "Would the current notification and assessment pathway detect a material supplier change before use?", approach: ["Walk a fictional site/process/sub-tier change.", "Trace notification, quarantine, evidence review and disposition roles.", "Record missing clauses and controls."], expectedOutputs: ["Change-response map", "Agreement gaps", "Escalation actions"], boundary: "Simulation is not supplier qualification, audit or legal review." },
    ],
    knowledgeChecks: [
      { question: "Why can the same chemical name represent different input risk?", expectedReasoning: "Manufacturer, site, grade, process, impurity profile, physical attributes, supply chain, storage and intended route use can differ materially." },
      { question: "What must a supplier approval scope specify?", expectedReasoning: "At minimum the material/grade, actual manufacturing and relevant testing sites, supply route, intended use, controls, restrictions and evidence state." },
      { question: "Why is downstream testing not a substitute for input control?", expectedReasoning: "Some input effects may be poorly detected, transform during processing or affect performance; control should be placed using route/process knowledge and capable measurement." },
    ],
    completionCriteria: ["Route and material scope are exact.", "Input and impurity hypotheses are traceable.", "Supplier/change/incoming controls have named owners.", "Approval and regulatory conclusions remain explicitly outside the package."],
  }),
  defineLearningFlow({
    packageId: "pharma-api-reaction-workup-scale-up",
    learningObjectives: ["Connect reaction and work-up mechanisms to material balance, impurity formation and control placement.", "Distinguish scale-dependent transport and equipment effects from chemistry alone.", "Design bounded scale-up evidence without publishing operating ranges or recipes."],
    knowledgeUnits: [
      { title: "Reaction network and impurity formation", explanation: "Desired conversion, competing reactions, degradation and carryover form a network influenced by inputs, sequence, time, temperature, mixing and exposure history.", decisionUse: "Use the network to decide what must be measured and where evidence is needed, not to publish a universal recipe." },
      { title: "Work-up as a control stage", explanation: "Quench, extraction, wash, phase split, concentration and exchange steps can create, remove or redistribute impurities and determine the burden entering isolation.", decisionUse: "Trace material and impurity fate through every handoff, including holds and recycle streams." },
      { title: "Scale translation", explanation: "Heat and mass transfer, mixing, addition, gas transfer, solids handling and equipment geometry can change with scale even when nominal setpoints match.", decisionUse: "Translate by mechanism and measurable performance rather than copying small-scale conditions." },
    ],
    workflowPhases: [
      { id: "scope", title: "Define route step and scale-up decision", objective: "Freeze reaction/work-up sequence, equipment concept, scales, sites and decision question.", activities: ["Record batch and process versions.", "Map equipment and material-contact differences.", "Name process safety, engineering, analytical and quality reviewers."], evidenceToCapture: ["Process description", "Scale/equipment comparison", "Decision boundary"], decisionGate: "No analysis proceeds with mixed route or equipment versions." },
      { id: "mechanism", title: "Map mechanisms and observables", objective: "Connect reaction/work-up mechanisms to measurable process and quality responses.", activities: ["Build desired and competing reaction hypotheses.", "Map quench/extraction/wash/concentration functions.", "Identify measurements and sampling limitations."], evidenceToCapture: ["Mechanism–response map", "Material/impurity balance", "Measurement limitations"], decisionGate: "Unmeasured mechanisms stay hypotheses and cannot become controls." },
      { id: "scale", title: "Translate scale-dependent phenomena", objective: "Identify which mixing, transfer, addition, hold and geometry differences could change performance.", activities: ["Compare equipment and operating modes.", "Map plausible scale sensitivities.", "Select engineering and chemical observables conceptually."], evidenceToCapture: ["Scale-risk register", "Equipment similarity/difference basis", "Monitoring questions"], decisionGate: "Nominal setpoint matching alone is insufficient evidence of scale comparability." },
      { id: "study", title: "Design scale-up and robustness evidence", objective: "Frame studies that separate chemistry, work-up and scale effects.", activities: ["Define factors and responses using risk/process knowledge.", "Plan material balance and impurity tracking.", "Predefine escalation for unsafe, inconclusive or discordant results."], evidenceToCapture: ["Study architecture", "Response/method rationale", "Site-owned protocol and safety controls"], decisionGate: "Atlas supplies no operating range, safe limit or acceptance criterion." },
      { id: "decide", title: "Record scale decision and downstream burden", objective: "Document supported conditions, unresolved risks and what isolation/analytical stages must receive.", activities: ["Separate observed performance from proposed control strategy.", "Record equipment and scale applicability.", "Carry impurity and hold questions forward."], evidenceToCapture: ["Scale-up decision record", "Open-risk actions", "Isolation-stage handoff"], decisionGate: "The output is review context, not process validation, safety authorization or manufacturing instruction." },
    ],
    evidenceActivities: [
      { title: "Reaction/work-up material-balance review", kind: "data-analysis", decisionQuestion: "Can desired material and key impurity observations be reconciled across reaction and work-up steps?", approach: ["Align charges, samples, phases, streams and methods.", "Record unmeasured or poorly recovered fractions.", "Challenge apparent loss or purge with sampling and method capability."], expectedOutputs: ["Step-wise balance map", "Unexplained-fate register", "Measurement actions"], boundary: "No yield target or purge factor is prescribed." },
      { title: "Scale-effect study frame", kind: "study-design", decisionQuestion: "Which scale-dependent mechanisms need evidence before the next scale decision?", approach: ["Compare geometry, mixing, heat/mass transfer and addition modes.", "Select process and quality responses conceptually.", "Define scale and equipment applicability explicitly."], expectedOutputs: ["Mechanism-based study questions", "Scale comparison matrix", "Review triggers"], boundary: "No equipment setting, process range or safety limit is provided." },
      { title: "Hold and interruption challenge", kind: "challenge-session", decisionQuestion: "Which planned or unplanned holds could change reaction, work-up or impurity outcomes?", approach: ["Map hold locations and material state.", "Review degradation, phase, temperature and resumption hypotheses.", "Assign study or procedural evidence needs."], expectedOutputs: ["Hold-risk map", "Evidence needs", "Escalation owners"], boundary: "No hold time is established." },
    ],
    knowledgeChecks: [
      { question: "Why can matching temperature setpoints fail to reproduce reaction performance at scale?", expectedReasoning: "Heat removal, mixing, addition distribution, measurement location, mass transfer and equipment response can differ with scale." },
      { question: "Why must work-up be included in impurity understanding?", expectedReasoning: "Work-up can transform, partition, concentrate, remove or introduce impurities and determines what enters isolation." },
      { question: "What is required before a correlation becomes a control strategy element?", expectedReasoning: "Plausible mechanism, capable measurement, relevant data, scope/applicability, robustness and accountable review are needed." },
    ],
    completionCriteria: ["Mechanisms and measurements are linked.", "Scale/equipment differences are explicit.", "Study and safety ownership are assigned.", "Downstream impurity and hold questions are transferred."],
  }),
  defineLearningFlow({
    packageId: "pharma-api-isolation-solid-state-impurity",
    learningObjectives: ["Connect isolation, drying and milling choices to solid-state form, particle attributes and impurity fate.", "Distinguish observed fate, plausible purge and demonstrated process capability.", "Frame solid-state and impurity studies without universal solvent, temperature, milling or acceptance settings."],
    knowledgeUnits: [
      { title: "Nucleation, growth and isolation history", explanation: "Supersaturation path, seeding, solvent composition, temperature history, agitation and isolation determine a material's solid-state and particle history.", decisionUse: "Trace exact batch history and evidence before attributing a form or particle result to one factor." },
      { title: "Drying, milling and physical attributes", explanation: "Residual solvent/moisture, temperature exposure, mechanical energy and handling can alter form, agglomeration, particle-size distribution and downstream behavior.", decisionUse: "Connect processing history to fit-for-purpose physical and analytical evidence." },
      { title: "Impurity fate and purge", explanation: "Impurities may react, partition, remain in mother liquor, co-precipitate, adsorb, occlude, transform or be introduced; observed reduction is process- and method-specific.", decisionUse: "Build a route- and step-specific fate argument with uncertainty visible." },
    ],
    workflowPhases: [
      { id: "scope", title: "Freeze isolation and material scope", objective: "Define route/process version, target form/material state, equipment, scale, storage and decision.", activities: ["Map crystallization through final handling.", "Record target and observed material descriptors.", "Identify solid-state, process, analytical and quality reviewers."], evidenceToCapture: ["Batch/process history", "Material and method identifiers", "Decision/applicability scope"], decisionGate: "Stop if samples or results cannot be tied to exact processing history." },
      { id: "map", title: "Map solid-state and impurity pathways", objective: "Connect unit-operation history to form, particle, solvent/moisture and impurity observations.", activities: ["Map nucleation/growth/isolation/drying/milling functions.", "Trace impurity hypotheses by step.", "Link each observation to method capability and sample history."], evidenceToCapture: ["Process–attribute map", "Impurity fate map", "Sample/method lineage"], decisionGate: "Unobserved purge or form conversion remains a hypothesis." },
      { id: "challenge", title: "Challenge sampling and measurement", objective: "Assess heterogeneity, sample preparation, method specificity and reporting limitations.", activities: ["Review sampling locations and representativeness.", "Compare orthogonal solid-state/particle evidence.", "Examine below-quantitation and recovery limitations."], evidenceToCapture: ["Sampling rationale", "Orthogonal evidence comparison", "Method-limit register"], decisionGate: "A single unqualified result cannot establish form, particle or impurity control." },
      { id: "study", title: "Frame isolation and fate studies", objective: "Define bounded studies for the mechanisms most likely to affect the decision.", activities: ["Select factors/responses conceptually.", "Preserve mother-liquor, cake, dried and milled sample links.", "Predefine handling of transformations and inconclusive results."], evidenceToCapture: ["Study questions", "Sample-chain plan", "Review/escalation rules"], decisionGate: "Site teams own solvents, temperatures, milling conditions, safety and acceptance criteria." },
      { id: "decide", title: "Record material-state and impurity decision", objective: "State what evidence supports for the exact process/material state and what remains open.", activities: ["Separate characterization from specification/disposition.", "Assign storage, handling and monitoring actions.", "Carry material attributes into drug-product formulation where relevant."], evidenceToCapture: ["Bounded conclusion", "Residual-risk register", "Drug-product handoff"], decisionGate: "Completion is not solid-form selection, specification approval or batch release." },
    ],
    evidenceActivities: [
      { title: "Impurity fate map", kind: "evidence-review", decisionQuestion: "What is observed, inferred and unknown about each relevant impurity across isolation and finishing?", approach: ["Trace formation/input and step-wise observations.", "Record partition, transformation and method hypotheses separately.", "Flag censored or unmatched data."], expectedOutputs: ["Observed-versus-hypothesized fate map", "Evidence gaps", "Study priorities"], boundary: "No universal purge factor or acceptable impurity level is created." },
      { title: "Solid-state stress study frame", kind: "study-design", decisionQuestion: "Which process or handling exposures could alter the material state relevant to the decision?", approach: ["Map plausible thermal, solvent, moisture and mechanical exposures.", "Select orthogonal characterization responses conceptually.", "Define sample history and applicability."], expectedOutputs: ["Exposure–response study questions", "Sample lineage plan", "Review boundaries"], boundary: "No process condition, form claim or design space is supplied." },
      { title: "Sampling representativeness challenge", kind: "challenge-session", decisionQuestion: "Do samples represent the isolated, dried and milled material states being discussed?", approach: ["Review sampling location/time and compositing.", "Compare within- and between-container observations where available.", "Assess preparation and method-induced artifacts."], expectedOutputs: ["Sampling-risk register", "Re-sampling or method questions", "Interpretation limits"], boundary: "The activity does not define a regulatory sampling plan." },
    ],
    knowledgeChecks: [
      { question: "Why is impurity reduction across isolation not automatically a purge factor?", expectedReasoning: "It may reflect sampling, phase recovery, method limits, batch context or a non-robust condition; demonstrated fate needs step-specific evidence and applicability." },
      { question: "Why must particle and solid-form results retain processing history?", expectedReasoning: "Crystallization, isolation, drying, milling, storage and sample preparation can all alter the observed material." },
      { question: "What is the difference between characterization and specification?", expectedReasoning: "Characterization builds understanding; a specification is a controlled acceptance framework justified for a defined material/product and lifecycle state." },
    ],
    completionCriteria: ["Process and sample histories are traceable.", "Observed and hypothesized fate are separated.", "Study questions retain safety and site ownership.", "Material-state limitations and downstream handoff are recorded."],
  }),
  defineLearningFlow({
    packageId: "pharma-api-analytical-lifecycle",
    learningObjectives: ["Connect analytical target profile, procedure development, validation, transfer and routine performance to intended use.", "Link specification and stability reasoning to process/impurity knowledge without creating criteria.", "Integrate method, process validation, investigation and commercial change evidence."],
    knowledgeUnits: [
      { title: "Analytical procedure lifecycle", explanation: "The analytical target profile, development knowledge, performance characteristics, control strategy, validation, transfer and monitoring remain linked to intended use and reportable result.", decisionUse: "Use the chain to identify whether a method remains fit for the current decision and lifecycle state." },
      { title: "Specification and stability basis", explanation: "Specifications combine process/product understanding, method capability, stability behavior, safety/quality considerations and regulatory commitments; they are not copied from one dataset or compendium alone.", decisionUse: "Trace every proposed criterion or shelf-life statement to its product-specific evidence and authority." },
      { title: "Commercial lifecycle integration", explanation: "Process validation, routine monitoring, deviations, OOS/OOT, method changes, transfers and stability signals can reopen analytical and control-strategy questions.", decisionUse: "Define triggers and owners so the evidence system learns without silently changing approved controls." },
    ],
    workflowPhases: [
      { id: "scope", title: "Freeze intended use and lifecycle state", objective: "Define analyte/attribute, matrix, reportable result, procedure version, site/instrument context and decision.", activities: ["Record analytical target and intended use.", "Map product/process and impurity context.", "Identify analytical, QC, statistics, stability, quality and regulatory reviewers."], evidenceToCapture: ["Intended-use statement", "Method/version/site identifiers", "Decision and filing context"], decisionGate: "No performance or transfer conclusion proceeds with an undefined intended use." },
      { id: "develop", title: "Map development knowledge and controls", objective: "Connect method variables, sample preparation, system suitability and robustness knowledge to reportable-result risk.", activities: ["Map method steps and variable hypotheses.", "Review selectivity and sample/standard stability questions.", "Separate system checks from method capability."], evidenceToCapture: ["Method knowledge map", "Risk/control rationale", "Unresolved robustness questions"], decisionGate: "System suitability cannot substitute for validation or sample-specific suitability." },
      { id: "validate-transfer", title: "Design validation and transfer evidence", objective: "Define performance evidence proportionate to intended use and receiving context.", activities: ["Map characteristics to intended-use risks.", "Define transfer/comparative or co-validation questions.", "Predefine deviations, equivalence claims and review roles."], evidenceToCapture: ["Performance evidence matrix", "Transfer design rationale", "Protocol ownership"], decisionGate: "No universal validation range, criterion or transfer acceptance rule is supplied." },
      { id: "monitor", title: "Review routine, stability and investigation signals", objective: "Assess whether procedure and specification assumptions remain credible during commercial use.", activities: ["Trend performance, reference and system signals.", "Connect OOS/OOT/deviation evidence to method and process context.", "Review stability-indicating capability and packaging/storage changes."], evidenceToCapture: ["Lifecycle trend package", "Investigation links", "Change triggers"], decisionGate: "Statistical signal, specification failure and batch disposition remain separate decisions." },
      { id: "decide", title: "Record lifecycle disposition and handoff", objective: "Document method fitness, open evidence, changes and commercial monitoring responsibilities.", activities: ["State scope and limitations of the conclusion.", "Assign remediation, revalidation or transfer actions.", "Link product/process changes to analytical impact review."], evidenceToCapture: ["Method lifecycle decision", "Action and ownership register", "Controlled change links"], decisionGate: "Completion is not method approval, specification approval, shelf-life authorization or batch release." },
    ],
    evidenceActivities: [
      { title: "Intended-use performance challenge", kind: "challenge-session", decisionQuestion: "Does the evidence demonstrate performance for the exact reportable result and decision?", approach: ["Map each performance characteristic to intended use.", "Challenge matrix, range, sample preparation and interference applicability.", "Record gaps hidden by aggregate validation summaries."], expectedOutputs: ["Characteristic–decision map", "Applicability gaps", "Evidence actions"], boundary: "No validation acceptance criterion is generated." },
      { title: "Method transfer simulation", kind: "transfer-simulation", decisionQuestion: "Can the receiving laboratory reproduce the method knowledge and identify context differences before execution?", approach: ["Walk samples, standards, instruments, software and calculations.", "Compare training, environment and local procedures.", "Record differences requiring protocol evidence."], expectedOutputs: ["Transfer readiness map", "Context-difference register", "Protocol questions"], boundary: "Simulation is not successful transfer, qualification or method approval." },
      { title: "Stability/specification evidence review", kind: "data-analysis", decisionQuestion: "What evidence supports the current analytical, stability and specification basis, and which signals could reopen it?", approach: ["Align results by batch, timepoint, condition, method and package.", "Review trends, censored data and method changes.", "Separate scientific interpretation from approved criteria."], expectedOutputs: ["Evidence chronology", "Trend and method limitations", "Lifecycle triggers"], boundary: "No shelf life, retest period or specification is set." },
    ],
    knowledgeChecks: [
      { question: "Why must analytical performance be tied to intended use?", expectedReasoning: "A method can perform adequately for one matrix, range or decision and be unsuitable for another; validation evidence is not context-free." },
      { question: "Does passing system suitability prove the reportable result is valid?", expectedReasoning: "No. It checks defined system conditions but does not by itself establish sample preparation, selectivity, matrix suitability, data integrity or overall procedure fitness." },
      { question: "What can reopen an analytical lifecycle decision?", expectedReasoning: "Product/process/matrix changes, method or instrument changes, transfer differences, stability signals, investigations, reference changes and performance trends can all reopen it." },
    ],
    completionCriteria: ["Intended use and method context are exact.", "Development/validation/transfer evidence is connected.", "Routine and stability signals have governance triggers.", "Approval, specification and release decisions remain controlled elsewhere."],
  }),
];
