import { qualityScoreSchema, type QualityAssetClass, type QualityScore } from "./content-quality.js";

export interface PaidAssetQualityRecord {
  id: string;
  name: string;
  product: "quality-lab" | "atlas-pro" | "career";
  assetClass: QualityAssetClass;
  strategicPriority: "core" | "compatibility";
  reviewStatus: "under-review" | "editorial-reviewed" | "sme-reviewed";
  score: QualityScore;
  limitations: string[];
}

function score(values: [number, number, number, number, number], criticalFails: string[] = []): QualityScore {
  return qualityScoreSchema.parse({
    provenance: values[0],
    actionability: values[1],
    applicability: values[2],
    workedExample: values[3],
    usability: values[4],
    criticalFails,
  });
}

export const PAID_ASSET_QUALITY: PaidAssetQualityRecord[] = [
  { id: "quality-lab-scope-diagnostic", name: "Atlas Quality Lab Scope Diagnostic", product: "quality-lab", assetClass: "paid-output", strategicPriority: "core", reviewStatus: "under-review", score: score([17, 19, 11, 8, 10], ["Controlled reviewer coverage is not yet recorded.", "Three accepted real engagements are not yet available."]), limitations: ["Pilot decision-support package; final controlled scope requires appointed reviewers and client records."] },
  { id: "quality-lab-blueprint", name: "Atlas Quality Lab Blueprint", product: "quality-lab", assetClass: "paid-output", strategicPriority: "core", reviewStatus: "under-review", score: score([19, 22, 12, 12, 11], ["Four review domains are not yet covered by appointed reviewers.", "Six evidence records remain open.", "Estimate-to-actual evidence from three accepted engagements is not yet available."]), limitations: ["Material outputs with blocking inputs or evidence-required status cannot be controlled-released."] },
  { id: "gmp-audit-kit", name: "GMP Audit Readiness Kit", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([16, 20, 11, 12, 13], ["Editorial and risk-based reviewer sign-off are not recorded."]), limitations: ["Checklist support does not replace a site audit program or authorized compliance assessment."] },
  { id: "oos-investigation-template", name: "OOS Investigation Template", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([20, 21, 13, 13, 13], ["Qualified OOS investigation and disposition review is not recorded."]), limitations: ["Qualified quality-unit oversight remains required for investigation and disposition."] },
  { id: "environmental-monitoring-checklist", name: "Environmental Monitoring Checklist", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([16, 20, 11, 13, 13], ["Site-specific contamination-control and qualified review are not recorded."]), limitations: ["Site CCS, process, method and current applicable requirements determine monitoring design."] },
  { id: "lab-water-selection-checklist", name: "Lab Water Selection Checklist", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([14, 19, 11, 12, 13], ["Compendial values require licensed current-edition verification.", "Qualified site-use review is not recorded."]), limitations: ["Water grade and limits depend on intended use, jurisdiction and approved site controls."] },
  { id: "pharma-api-impurity-control", name: "Pharma API Process & Impurity Control Evidence Map", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([23, 23, 14, 14, 14], ["Qualified process chemistry, process engineering, analytical development, impurity-safety, API QC, quality and regulatory CMC review is not recorded.", "No real permissioned impurity-control case with corrections, decisions and actual process/product outcomes is available."]), limitations: ["The package structures evidence and does not establish chemistry, starting-material acceptability, impurity identity or safety, analytical suitability, purge, process capability, specification, validation, filing, commercial authorization or batch disposition."] },
  { id: "pharma-api-starting-material-input-control", name: "Pharma API Starting Material & Input Control Evidence Map", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([23, 23, 14, 14, 14], ["Qualified synthetic-process, supplier-quality, API analytical/QC, quality, manufacturing/validation and regulatory CMC review is not recorded.", "No real permissioned starting-material justification or supplier-change case with corrections and decision outcomes is available."]), limitations: ["The package structures evidence and does not establish chemistry, commodity status, starting-material acceptability, supplier approval, specification, method suitability, reduced testing, filing acceptance, manufacturing authorization or batch disposition."] },
  { id: "pharma-api-analytical-lifecycle", name: "Pharma API Analytical & Lifecycle Control Evidence Map", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([23, 23, 14, 14, 14], ["Qualified API analytical development, QC, statistics, stability, validation, quality and regulatory CMC review is not recorded.", "No real permissioned API method lifecycle, stability or transfer case with corrections and authorized outcomes is available."]), limitations: ["The package structures evidence and does not establish a method, validation, system suitability, specification, stability condition, shelf life, transfer acceptance, filing decision or batch disposition."] },
  { id: "biopharma-upstream-control", name: "Biopharma Upstream Control Evidence Map", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([21, 22, 14, 14, 14], ["Qualified upstream/MSAT, analytical development, quality, and regulatory CMC review is not recorded.", "No real permissioned process-characterization or scale-change case is available."]), limitations: ["The package structures evidence and does not establish product-specific CQAs, CPPs, causality, ranges, validation status, comparability, or regulatory acceptance."] },
  { id: "biopharma-downstream-clearance", name: "Biopharma Downstream Purification & Clearance Evidence Map", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([22, 22, 14, 14, 14], ["Qualified downstream, analytical, viral-safety, quality, and regulatory CMC review is not recorded.", "No real permissioned downstream change, scale-down, resin/membrane lifecycle, or clearance case is available."]), limitations: ["The package structures evidence and does not establish a purification train, product-specific impurity or viral clearance, causality, robustness, ranges, lifetimes, validation status, comparability, or regulatory acceptance."] },
  { id: "biopharma-formulation-stability", name: "Biopharma Formulation & Stability Evidence Map", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([22, 22, 14, 14, 14], ["Qualified formulation, fill-finish, analytical, stability, container, quality, validation, and regulatory CMC review is not recorded.", "No real permissioned formulation, fill-finish, container, shipping, storage, or stability change case is available."]), limitations: ["The package structures evidence and does not establish a formulation, degradation mechanism, process, presentation, container suitability or integrity, sterility assurance, stability protocol, shipping qualification, storage condition, shelf life, validation status, comparability, or regulatory acceptance."] },
  { id: "biopharma-analytical-control-strategy", name: "Biopharma Analytical Control Strategy Evidence Map", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([23, 22, 14, 14, 14], ["Qualified product-quality, analytical, bioassay/statistics, reference-standard, QC, quality, validation, and regulatory CMC review is not recorded.", "No real permissioned analytical-strategy, specification, reference-transition, method-transfer, or comparability case is available."]), limitations: ["The package structures evidence and does not establish product CQAs, analytical procedures, validation or transfer designs, reference values or suitability, specifications, acceptance criteria, comparability, regulatory acceptance, or batch disposition."] },
  { id: "biopharma-technology-transfer", name: "Biopharma Technology Transfer Evidence Map", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([23, 22, 14, 14, 14], ["Qualified transfer, process/MSAT, manufacturing, engineering/automation, analytical/QC, validation, quality, supply-chain, and regulatory CMC review is not recorded.", "No real permissioned biologics site-transfer case with execution, correction, acceptance, and actual-outcome evidence is available."]), limitations: ["The package structures evidence and does not establish facility or equipment suitability, material equivalence, process robustness, analytical equivalence, product comparability, validation, regulatory acceptability, execution readiness, routine readiness, site approval, or batch disposition."] },
  { id: "biopharma-materials-control", name: "Biopharma Materials & Single-Use Control Evidence Map", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([23, 22, 14, 14, 14], ["Qualified raw-material/material-science, supplier-quality, supply-chain, process/MSAT, single-use/E&L/toxicology, microbiology/viral-safety, analytical, validation, quality, and regulatory CMC review is not recorded.", "No real permissioned material, supplier, sub-tier, sterilization, or single-use change case with implementation and actual-outcome evidence is available."]), limitations: ["The package structures evidence and does not establish material suitability, supplier approval, specification adequacy, test reduction, contamination or viral safety, single-use-system suitability, extractables/leachables safety, process validation, product comparability, regulatory acceptability, change implementation, supply continuity, or batch disposition."] },
  { id: "biopharma-cell-substrate-control", name: "Biopharma Cell Substrate & Bank Lifecycle Evidence Map", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([23, 22, 14, 14, 14], ["Qualified cell-line development, molecular characterization, cell-bank manufacturing/custody, biosafety, viral-safety, process/MSAT, analytical/product-quality, statistics, validation, quality, and regulatory CMC review is not recorded.", "No real permissioned cell-line, replacement-bank, production-age, storage/site, or genetic-stability case with implementation and actual-outcome evidence is available."]), limitations: ["The package structures evidence and does not establish cell-line suitability, construct integrity, clone selection, bank release, purity, genetic/phenotypic stability, adventitious-agent or viral-safety status, production-age limits, process validation, product comparability, regulatory acceptability, authorized bank use, or batch disposition."] },
  { id: "biopharma-process-validation-cpv", name: "Biopharma Process Validation & CPV Evidence Map", product: "atlas-pro", assetClass: "pro", strategicPriority: "core", reviewStatus: "under-review", score: score([23, 23, 14, 14, 14], ["Qualified process-development/MSAT, manufacturing, validation, engineering/automation/data, analytical/QC, statistics, product-quality, quality, and regulatory CMC review is not recorded.", "No real permissioned PPQ-to-CPV or revalidation case with corrections, decisions and actual process/product outcomes is available."]), limitations: ["The package structures evidence and does not establish product-specific CQAs or CPPs, ranges, qualification, PPQ design or success, CPV method or limits, process capability, validated state, comparability, regulatory acceptability, routine authorization, or batch disposition."] },
  { id: "bi-workflow-checklist", name: "BI Workflow Checklist", product: "atlas-pro", assetClass: "pro", strategicPriority: "compatibility", reviewStatus: "under-review", score: score([8, 12, 7, 5, 7], ["Content Quality Contract v2 review is incomplete."]), limitations: ["Accessible to existing users but excluded from promoted workflows."] },
  { id: "culture-media-selection-guide", name: "Culture Media Selection Guide", product: "atlas-pro", assetClass: "pro", strategicPriority: "compatibility", reviewStatus: "under-review", score: score([8, 12, 7, 5, 7], ["Content Quality Contract v2 review is incomplete."]), limitations: ["Accessible to existing users but excluded from promoted workflows."] },
  { id: "data-integrity-self-check", name: "Data Integrity Self-Check", product: "atlas-pro", assetClass: "pro", strategicPriority: "compatibility", reviewStatus: "under-review", score: score([8, 12, 7, 5, 7], ["Content Quality Contract v2 review is incomplete."]), limitations: ["Accessible to existing users but excluded from promoted workflows."] },
  { id: "microbiology-qc-starter-pack", name: "Microbiology QC Starter Pack", product: "atlas-pro", assetClass: "pro", strategicPriority: "compatibility", reviewStatus: "under-review", score: score([8, 12, 7, 5, 7], ["Content Quality Contract v2 review is incomplete."]), limitations: ["Accessible to existing users but excluded from promoted workflows."] },
  { id: "career-operating-blueprint", name: "Personalized Career Operating Blueprint", product: "career", assetClass: "paid-output", strategicPriority: "core", reviewStatus: "under-review", score: score([14, 21, 12, 13, 15], ["Hiring-manager or QC leadership review is not recorded.", "Five real transition pilots are not yet available."]), limitations: ["Decision support only; it does not guarantee hiring, promotion, compensation or immigration outcomes."] },
];
