import { Link } from "wouter";

import { getStageResourceCoverage, RESOURCE_AREA_PATHS, type ResourceArea, type ResourceSelection } from "@/data/resourceConnections";
import { analytics, capture } from "@/hooks/use-analytics";

const statusLabel = { mapped: "Mapped", "under-review": "Under review", "evidence-required": "Evidence required", "specialist-review-required": "Specialist review", "not-covered": "Not covered", "no-current-change": "Watch active" } as const;
const statusStyle = { mapped: "border-teal-300/25 bg-teal-300/[0.07] text-teal-200", "under-review": "border-violet-300/25 bg-violet-300/[0.06] text-violet-200", "evidence-required": "border-amber-300/25 bg-amber-300/[0.06] text-amber-200", "specialist-review-required": "border-sky-300/25 bg-sky-300/[0.06] text-sky-200", "not-covered": "border-rose-300/25 bg-rose-300/[0.06] text-rose-200", "no-current-change": "border-white/10 bg-white/[0.03] text-slate-400" } as const;

export function StageCoverageDashboard({ selection, className = "" }: { selection: ResourceSelection; className?: string }) {
  const coverage = getStageResourceCoverage(selection);
  if (!coverage) return null;
  return <section className={`border-t border-white/[0.08] px-4 py-4 ${className}`} aria-label="Resource coverage dashboard"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-slate-600">Coverage registry v3</p><p className="mt-1 text-xs font-semibold text-slate-300">Connected resources expose evidence, review and not-covered states explicitly.</p></div><span className="rounded-full border border-white/10 px-2.5 py-1 text-[9px] font-bold text-slate-500">{Object.keys(coverage.areas).length} / {Object.keys(coverage.areas).length} areas</span></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{(Object.keys(coverage.areas) as ResourceArea[]).map((area) => { const item = coverage.areas[area]; return <Link key={area} href={`${RESOURCE_AREA_PATHS[area]}?system=${coverage.system.id}&stage=${coverage.stage.id}&source=coverage-dashboard`} onClick={() => { capture("resource_coverage_opened", { system_id: coverage.system.id, stage_id: coverage.stage.id, area, status: item.status }); if (item.status === "evidence-required" || item.status === "not-covered") analytics.coverageGapOpened(item.connections.flatMap((connection) => connection.decisionPackageIds)[0] ?? "unmapped", coverage.system.id, coverage.stage.id); }} className={`rounded-xl border p-3 outline-none transition hover:-translate-y-0.5 focus-visible:ring-2 focus-visible:ring-teal-300/40 ${statusStyle[item.status]}`}><span className="block text-[9px] font-bold uppercase tracking-wider">{area}</span><strong className="mt-1 block text-[10px] leading-4">{statusLabel[item.status]}</strong><span className="mt-1 block text-[9px] opacity-70">{item.connections.length} connection{item.connections.length === 1 ? "" : "s"}</span></Link>; })}</div></section>;
}
